### ISSUE TITLE
Should closing window automatically switch to other?

### ISSUE THREAD

**Issue by agzam** [ch11ng/exwm#460] opened 2018-08-01 17:23 UTC
This is kinda annoying, I'll try to describe it.

If you have an app, let's say a browser, with multiple windows. You close one of the windows, exwm switches to some kind of helper buffer (which is pretty useless)

So try this:
- open a browser
- open a new window (not a tab, a window)
- close the window

See, what I think should happen - exwm should switch to the first window, but instead for me it opens that useless buffer. Any suggestions for a workaround?

**Comment by sarg** [comment] 2018-08-02 13:02
It has nothing to do with EXWM. Buffer management is done by emacs. Usually when you `kill-buffer`, previous buffer from [Window history](https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-History.html#Window-History) is shown. You may alter this behaviour by adding a `kill-buffer-hook`.

**Comment by agzam** [comment] 2018-08-03 01:53
no I understand that it has very little (or really nothing) to do with EXWM. Just wanted to know if people experiencing similar behavior and if there are known workarounds.

**Comment by agzam** [comment] 2018-08-03 03:53
I might have fixed it for myself:

(defun fix-exwm-kill-buffer ()
  (when (derived-mode-p 'exwm-mode)
    (let* ((buf (buffer-name (current-buffer)))
           (suffix (replace-regexp-in-string "<\\([0-9]+\\)>" "" buf))
           (fnd (car (car (-filter (lambda (x)
                                     (let ((b (buffer-name (first x))))
                                       (and (cl-search suffix b)
                                            (not (string= buf b)))))
                                   (window-prev-buffers))))))
      (when fnd (switch-to-buffer fnd)))))

**Comment by WJCFerguson** [comment] 2018-08-03 12:37
I'm afraid I don't regularly get your symptoms (though I have *seen* these ghost buffers, where it renders an empty Emacs window for the X window without the actual X window visible - just not consistently).

**Comment by ch11ng** [comment] 2018-08-05 14:00
I agree with @WJCFerguson.  If nothing is misconfigured then this is a bug.  @agzam Could you provide a reliable way to reproduce this with a minimal configuration?

**Comment by ch11ng** [comment] 2018-08-12 11:26
> What minimal configuration would it be?

Usually I mean configuring vanilla Emacs with `exwm-config-default` but other configurations may be included when necessary.  And I understand with spacemacs this is not possible.  I think it's time to give vanilla Emacs a try; you'll find it pleasant to work with. 

> To reproduce it you can try opening a browser, then creating multiple new browser windows, then delete (kill the buffer). You would expect it to switch to previous browser window, but it shows a ghost buffer.

I've tried that but could not reproduce it unfortunately.

**Comment by medranocalvo** [comment] 2018-08-16 17:11
I think there are two issues at play here.  The issue with a blank buffer appearing in stead of your browser window is probably fixed by #469.  Please, test it.

The second is due to `exwm-mode` buffers having a limitation compared with regular Emacs buffers: they may be shown in at most exactly one window.  This has led to weirdness when switching buffers before, in particular the last buffer (see #145 for an example).

I don't experience the issues @agzam does.

@agzam: you can try with a minimal configuration as follows:
~~~
emacs -Q -L /path/to/exwm/ -L /path/to/xelb/ \
        --eval '(require 'exwm)' \
        --eval '(exwm-init)'
~~~

Please, check whether you can reproduce the issue that way.

**Comment by medranocalvo** [comment] 2018-08-30 19:02
@agzam, could you check whether last commits solve this issue?

**Comment by medranocalvo** [comment] 2018-10-02 13:57
@agzam, I believe this issue is fixed in the last commits.  Please, reopen if that's not the case.

**Closed by medranocalvo** 2018-10-02 13:57 UTC
