### ISSUE TITLE
progn: [XELB] Sync timeout

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#48] opened 2015-08-26 12:41 UTC
when i git pull exwm, the error is showed: 

progn: [XELB] Sync timeout

**Comment by ch11ng** [comment] 2015-08-26 13:01
Perhaps you should provide more details about this. What does "git pull exwm" mean? Is it reproducible?

**Comment by tumashu** [comment] 2015-08-26 13:22
sorry, after I "git pull" to newest exwm code, when i launch exwm, it only show "progn: [XELB] Sync timeout"
and no other error info....

**Comment by ch11ng** [comment] 2015-08-26 13:40
Putting `(setq xcb:debug-on t)` and `(setq exwm-debug-on t)` in your `.emacs` before loading these libraries can provide more info, I think.

**Comment by tumashu** [comment] 2015-08-27 10:47
The output is like this:
```
[XELB LOG] Setup response: [1 0 11 0 0 0 211 5 32 16 177 0 0 0 128 2 255 255 31 0 0 1 0 0 20 0 255 255 1 7 0 0 32 32 8 255 0 0 0 0 84 104 101 32 88 46 79 114 103 32 70 111 117 110 100 97 116 105 111 110 1 1 32 0 0 0 0 0 4 8 32 0 0 0 0 0 8 8 32 0 0 0 0 0 15 16 32 0 0 0 0 0 16 16 32 0 0 0 0 0 24 32 32 0 0 0 0 0 32 32 32 0 0 0 0 0 183 2 0 0 32 0 0 0 255 255 255 0 0 0 0 0 3 0 66 0 86 5 0 3 105 1 203 0 1 0 1 0 33 0 0 0 1 0 24 7 24 0 239 0 0 0 0 0 33 0 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 34 0 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 201 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 202 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 203 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 204 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 205 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 206 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 207 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 208 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 209 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 210 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 211 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 212 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 213 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 214 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 215 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 216 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 217 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 218 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 219 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 220 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 221 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 222 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 223 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 224 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 225 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 226 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 227 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 228 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 229 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 230 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 231 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 232 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 233 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 234 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 235 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 236 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 237 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 238 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 239 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 240 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 241 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 242 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 243 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 244 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 245 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 246 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 247 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 248 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 249 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 250 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 251 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 252 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 253 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 254 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 255 1 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 0 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 1 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 2 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 3 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 4 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 5 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 6 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 7 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 8 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 9 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 10 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 11 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 12 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 13 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 14 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 15 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 16 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 17 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 18 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 19 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 20 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 21 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 22 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 23 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 24 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 25 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 26 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 27 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 28 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 29 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 30 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 31 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 32 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 33 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 34 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 35 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 36 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 37 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 38 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 39 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 40 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 41 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 42 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 43 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 44 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 45 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 46 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 47 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 48 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 49 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 50 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 51 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 52 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 53 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 54 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 55 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 56 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 57 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 58 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 59 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 60 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 61 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 62 2 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 63 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 64 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 65 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 66 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 67 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 68 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 69 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 70 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 71 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 72 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 73 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 74 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 75 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 76 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 77 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 78 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 79 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 80 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 81 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 82 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 83 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 84 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 85 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 86 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 87 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 88 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 89 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 90 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 91 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 92 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 93 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 94 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 95 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 96 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 97 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 98 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 99 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 100 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 101 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 102 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 103 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 104 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 105 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 106 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 107 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 108 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 109 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 110 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 111 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 112 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 113 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 114 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 115 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 116 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 117 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 118 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 119 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 120 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 121 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 122 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 123 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 124 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 125 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 126 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 127 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 128 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 129 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 130 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 131 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 132 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 133 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 134 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 135 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 136 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 137 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 138 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 139 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 140 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 141 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 142 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 143 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 144 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 145 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 146 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 147 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 148 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 149 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 150 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 151 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 152 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 153 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 154 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 155 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 156 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 157 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 158 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 159 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 160 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 161 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 162 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 163 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 164 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 165 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 166 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 167 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 168 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 169 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 170 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 171 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 172 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 173 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 174 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 175 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 176 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 177 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 178 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 179 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 180 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 181 2 0 0 5 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 8 0 0 0 0 0 0 0 15 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 32 0 1 0 0 0 0 0 96 0 0 0 4 8 0 1 0 0 255 0 0 255 0 0 255 0 0 0 0 0 0 0]
[XELB LOG] Cache request: [eieio-class-tag--xcb:ChangeWindowAttributes t t 2 1 131767 2048 (expression (xcb:-fieldref (quote value-mask)) cases ((xcb:CW:BackPixmap background-pixmap) (xcb:CW:BackPixel background-pixel) (xcb:CW:BorderPixmap border-pixmap) (xcb:CW:BorderPixel border-pixel) (xcb:CW:BitGravity bit-gravity) (xcb:CW:WinGravity win-gravity) (xcb:CW:BackingStore backing-store) (xcb:CW:BackingPlanes backing-planes) (xcb:CW:BackingPixel backing-pixel) (xcb:CW:OverrideRedirect override-redirect) (xcb:CW:SaveUnder save-under) (xcb:CW:EventMask event-mask) (xcb:CW:DontPropagate do-not-propogate-mask) (xcb:CW:Colormap colormap) (xcb:CW:Cursor cursor))) unbound unbound unbound unbound unbound unbound unbound unbound unbound unbound unbound 1048576 unbound unbound unbound]
[XELB LOG] Cache request: [eieio-class-tag--xcb:GetInputFocus t t 43]
[XELB LOG] Error received: [0 3 1 0 183 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Quit

```

**Comment by ch11ng** [comment] 2015-08-27 11:11
Are you using the latest XELB?

**Comment by tumashu** [comment] 2015-08-27 11:18
xelb use newest code

**Comment by ch11ng** [comment] 2015-08-27 11:45
This is due to a typo in XELB which I think is fixed by now. Please update XELB and try if it works.

**Comment by tumashu** [comment] 2015-08-27 11:54
works, thanks!

**Closed** 2015-08-27 11:55 UTC
