### ISSUE TITLE
react on-MapRequest

### ISSUE THREAD

**Issue by zevlg** [ch11ng/exwm#89] opened 2015-10-29 00:27 UTC
MapRequest may occur not only at the initial X client state transition, but also in runtime.  At that time parent of MapRequest may differ from root window.  The best example of such situation is `M-x webjump RET xxx RET yyy` while your default browser is running in background.   EXWM currently handles this situation incorrectly: just maps browser's window, without actually switching to it's buffer

**Comment by ch11ng** [comment] 2015-10-29 04:29
Thanks.  Fixed in d9b4ba0265fc1674b1205a11e838f86bce434b13.

**Closed by ch11ng** 2015-10-29 04:29 UTC

**Comment by zevlg** [comment] 2015-10-29 08:17
With this change EXWM just ignores runtime MapRequests, so `M-x webjump RET xxx RET yyy` opens page in background firefox, but do not switch to it.  I think EXWM should switch to X client instead by default, also the behaviour might be configurable in situations like:

 * What to do if X client wants to map in current workspace?
 * What to do if X client wants to map in another workspace?
 * What to do if floating X client wants to map?

Possible configuration might be:

* Always pop to client (switch workspace if necessary)
* Always ignore
* Visually notify user (in modeline or echo area) that urgent client is available.

**Comment by ch11ng** [comment] 2015-10-29 09:27
The problem is not all browsers make a MapRequest in this case.  Chromium is one such exception.  So your proposal cannot be implemented consistently, I'm afraid.
