### ISSUE TITLE
EXWM buffers not resized after randr change

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#166] opened 2016-06-01 21:46 UTC
Steps to reproduce:

1. Attach external monitor with different resolution and set xrandr and exwm-randr in such way that these two displays have different resolutions ( via exwm-randr-refresh-hook for example).

2. Open EXWM buffer on one display.

3. Detach monitor or change xrandr so that monitor is disabled.

4. Check one of the windows that were on the removed display, it should have wrong size (if removed display had bigger resolution you should see just part of the X window ).  It is resized correctly after you perform something that "alters layout" or forces redraw like opening helm window.

**Comment by ch11ng** [comment] 2016-06-02 12:47
I can't seems to reproduce this.  Could you show me the xrandr commands?

**Comment by fm4d** [comment] 2016-06-02 19:50
Nothing special, just "xrandr  --output xxx --output xxx --auto". Btw this problem is new and I have not altered my multihead setup for some time.

**Comment by ch11ng** [comment] 2016-06-02 23:19
> Nothing special, just "xrandr --output xxx --output xxx --auto". Btw this problem is new and I have not altered my multihead setup for some time.

Actually the RandR module of EXWM has not been massively revised since February.  Could you also provide a log file?

**Comment by fm4d** [comment] 2016-06-07 19:20
Thats all I got from `*Messages*` when I disconnect/reconnect monitor (and one EXWM buffer):

```
[EXWM] (RandR) ScreenChangeNotify
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 nil VGA1 nil VIRTUAL1 nil)
[EXWM] (RandR) ScreenChangeNotify
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 [eieio-class-tag--xcb:RECTANGLE t 1366 0 1920 1080] VGA1 nil VIRTUAL1 nil)
[EXWM] (RandR) ScreenChangeNotify
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 nil VGA1 nil VIRTUAL1 nil)
Quit
[EXWM] (RandR) ScreenChangeNotify
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 [eieio-class-tag--xcb:RECTANGLE t 1366 0 1920 1080] VGA1 nil VIRTUAL1 nil)
```

**Comment by ch11ng** [comment] 2016-06-11 11:12
The log seems correct except that workspaces are not refreshed (which should be triggered by `window-configuration-change-hook`).  I wonder if workspaces were actually resized.  Could you provide the output of `xwininfo -tree -root` together with the log? Thanks!

**Comment by fm4d** [comment] 2016-06-11 15:42
Log:
```
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 [eieio-class-tag--xcb:RECTANGLE t 1366 0 1920 1080] VGA1 nil VIRTUAL1 nil)
[EXWM] (RandR) ScreenChangeNotify
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 [eieio-class-tag--xcb:RECTANGLE t 1366 0 1920 1080] VGA1 nil VIRTUAL1 nil)
[EXWM] (RandR) ScreenChangeNotify
[EXWM] (randr) outputs: (LVDS1 [eieio-class-tag--xcb:RECTANGLE t 0 0 1366 768] DP1 nil DP2 nil DP3 nil HDMI1 nil HDMI2 nil HDMI3 [eieio-class-tag--xcb:RECTANGLE t 1366 0 1920 1080] VGA1 nil VIRTUAL1 nil)
```

and xwininfo: https://gist.github.com/fm4d/3dbc62c77d7c75b9644861e230d34133

I use emacs master, I will try downgrading and see if it helps.

**Comment by ch11ng** [comment] 2016-06-12 06:18
From the output of xwininfo, I can see some X windows with their containers not getting resized.  I tried Emacs master but cannot reproduce it either.  I cannot figure out the problem from the information provided thus far.  Please make sure your Emacs is up to date (either Emacs 25 or master) and provide the output of xwininfo before and after each step.  Also please point out which X windows are not properly resized.  Thanks!

**Comment by ch11ng** [comment] 2016-08-12 12:53
The cause of this issue seems to be identical to that of #177 , and should have been resolved.  I'm closing it now.  Please reopen it if the problem persists.

**Closed by ch11ng** 2016-08-12 12:53 UTC
