### ISSUE TITLE
flickering pixels with non-Emacs window open

### ISSUE THREAD

**Issue by kahrkunne** [ch11ng/exwm#264] opened 2017-06-05 14:18 UTC
If I have non-Emacs window open next to an Emacs window, there'll be some flickering pixels on the fringe between the two.

Tested:

Bigger chrome window on the left, smaller eshell window on the right: flickers white pixels on the edge of the eshell window

Bigger eshell window on the left, smaller chrome window on the right: flickers pixels of the same colour as my Emacs background on the edge of the Chrome window

Setup:

OS: Arch Linux

GPU: Nvidia GTX 1050 Ti 

Drivers: Nvidia proprietary

**Comment by ch11ng** [comment] 2017-06-11 17:59
When you said "edge" did you mean the window divider of Emacs? Could you provide some screenshots to illustrator this?

**Comment by ch11ng** [comment] 2018-10-21 14:58
I think this problem is fixed with release 0.20 so I'm closing it now.  Please reopen it if the problem is still there.

**Closed by ch11ng** 2018-10-21 14:58 UTC
