### ISSUE TITLE
google-chrome doesn't start after pkill-emacs

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#27] opened 2015-08-15 20:57 UTC
I am not sure if this is related to exwm or not...but this doesn't happen with other window managers, so I am posting it in here.

If I exit the session using kill-emacs function, then google-chrome seems to shutdown correctly. If I relogin and run s-& google-chrome, it opens fine.

On the other hand, if I exit the session using "pkill emacs", google-chrome doesn't startup after relogin.

Off-topic: I have to pkill emacs sometimes because exwm hangs after heavy use. I am not able to reproduce this consistently. When this happens, emacs CPU usage remains low, but keyboard events do nothing -- I suspect some locking issue, but am not sure.

**Comment by ch11ng** [comment] 2015-08-16 01:55
> On the other hand, if I exit the session using "pkill emacs", google-chrome doesn't startup after relogin.

Does google-chrome completely fail to start? Any error message?

> Off-topic: I have to pkill emacs sometimes because exwm hangs after heavy use. I am not able to reproduce this consistently. When this happens, emacs CPU usage remains low, but keyboard events do nothing -- I suspect some locking issue, but am not sure.

This is surely a serious problem. Perhaps because the input focus is lost.

**Comment by bvk** [comment] 2015-08-17 18:30
google-chrome hangs in the middle (I think it did not close properly and release any on-disk locks, etc.). I see exwm buffer name is changed to Google-chrome, but it doesn't display anything. Maybe, pkill-emacs doesn't send "close" message to exwm managed windows?

**Comment by ch11ng** [comment] 2015-08-18 12:01
I cannot reproduce this issue with google-chrome-stable or chromium, so could you please help me do some simple tests?

1. Add `(setq exwm-debug-on t)` before loading EXWM in your `.emacs`.
2. Start EXWM, launch chrome and
 - save the log in the `*Messages*` buffer,
 - save the output of `xwininfo -root -tree`.
3. `pkill` Emacs and repeat *2*.

I think the differences between these tests may tell something.

**Comment by bvk** [comment] 2015-08-18 18:40
I must admit my setup was little bit different from what is mentioned in the Configuration/Usage pages. I actually start the session using emacsclient -a="" -c "$@" command -- which starts emacs daemon in the background and opens the initial emacs-gtk frame.

I just noticed that exwm reports an error in the beginning:

Starting Emacs daemon.
[EXWM] Not running under X environment
When done with this frame, type C-x 5 0

I am not sure of it's implication, but I suppose, definitely not good :)

So, let me change my setup to run emacs binary directly and I will re-open this ticket if I see the same issue again and will include the above requested debug data.

**Comment by bvk** [comment] 2015-08-19 21:18
Ok, I this issue again. Here are somewhat relevant logs.

 *Messages* buffer when google-chrome doesn't appear: http://pastebin.com/gEhYVr15
xwininfo when google-chrome doesn't appear: http://pastebin.com/6sUREUZD

*Messages* buffer when google-chrome comes up fine: http://pastebin.com/uNECC3Cc
xwininfo when google-chrome comes up fine: http://pastebin.com/Q9MNzhDv

Also, this time, when google-chrome did not appear, I just left the workspace as it is and started working in another workspace. After sometime and I noticed that windows in the workspace began to display a white blocks in the middle (I suspect google-chrome may wanted to display a message box or something which doesn't get printed to the screen) that disappears when I type "enter" key.  I sometimes also notice a double status-bar like the one attached in the picture.
![fullsizerender](https://cloud.githubusercontent.com/assets/52023/9369316/162d8eba-467d-11e5-986b-cb0895aaad49.jpg)

**Comment by ch11ng** [comment] 2015-08-20 13:29
I think the problem has something to do with the X window titled "Page Unresponsive" (ID 0x140003b in http://pastebin.com/gEhYVr15), which is probably the white block you noticed. This X window was clearly managed by EXWM. Did it appear as a floating window? The `xprop` output about this X window would also be helpful.

> I sometimes also notice a double status-bar like the one attached in the picture.

I sometimes also encounter such problem, where the ghost bottom mode-line does not actually work. But your case seems a bit different since the bottom mode-line is newer (or updated, inferred from the time). Maybe it's because Emacs want to resize itself, but EXWM does not honor such requests. I don't have any reliable way to reproduce this problem though.

**Comment by ch11ng** [comment] 2015-08-27 06:29
Hi @bvk,

I revisited this issue today and still could not reproduce it by any means. Each time google-chrome just prompts me to restore tabs. I wonder if you have ever encountered this issue in the past few days (and if EXWM still hangs).

Your log file http://pastebin.com/6sUREUZD indicates that google-chrome did not finish startup since its main window has no child (it should have one normally). It seems the same happened to the X window titled "Page Unresponsive"; it also lacks a child window. In my case, the "Page Unresponsive" window created by google-chrome always appears normally, though not because of `pkill emacs`.

**Comment by ch11ng** [comment] 2015-09-19 12:23
It has been a long time since the last report, so I close this issue for now. Please reopen it if you ever encounter it again.

**Comment by 11111000000** [comment] 2016-11-04 20:58
A have this issue too. Lastest malpa exwm. google-chrome-stable. archlinux. Simple emacs config + stock exwm init scripts.

**Comment by ch11ng** [comment] 2016-11-05 15:51
@11111000000,

Any ideas on how to reproduce it reliably?

**Comment by medranocalvo** [comment] 2018-11-07 15:03
Hello @agzam.  It sounds annoying, indeed.

Can you reproduce at will?  If so, enable debugging and start a new session, reproduce the issue, save the log and post it here (after review).  Also the output of `xwininfo -root -tree`.

How do you start Emacs/EXWM?

@bvk, @11111000000: does this still happen to you on ArchLinux?  Could you help @agzam?

**Comment by 11111000000** [comment] 2018-11-09 10:30
I'm on nixos for 2 years now, and all work's fine

**Comment by agzam** [comment] 2018-11-13 05:31
I made a comment https://github.com/ch11ng/exwm/issues/487#issuecomment-438142036. I think I finally have fixed my woes with sudden death of Chrome (I really hope so)

**Comment by ch11ng** [comment] 2018-11-18 06:38
@agzam Any update? If this is really related to notification then does running a notification daemon like dunst fix it?

**Comment by agzam** [comment] 2018-11-18 08:06
I have dunst installed and enabled and it works for other things, yet that did not fix the issue. Only disabling Chrome flags did. After setting the flags Chrome has died in the similar fashion only once, not sure what have caused it. I will keep an eye on the things. Maybe will try to enable flags later and see what happens. I am still not 100% confident that it indeed fixed it. Things is - I cannot use my Linux computer at work and my daily exposure to EXWM currently is somewhat limited.

**Comment by medranocalvo** [comment] 2019-07-23 14:56
Closing as there's no new information since long ago.  Reopen as needed.

**Closed by medranocalvo** 2019-07-23 14:56 UTC
