### ISSUE TITLE
Latest master breaks s-; shortcut

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#451] opened 2018-06-28 12:57 UTC
I tried to switch to latest `master` commit for both exwm and xelb. I had to go back to previous version (1 commit for exwm, 2 commits for xelb) because some of my shortcuts didn't work anymore in application windows. For example, I have this in my [init.el](https://github.com/DamienCassou/emacs.d):

```emacs
(exwm-input-set-key (kbd "s-;") #'other-frame)
```

and I use `s-;` to switch between my 2 screens. This shortcut doesn't work anymore (it just prints `;`) when used from an application (e.g., slack or firefox).

**Comment by jabranham** [comment] 2018-06-28 22:42
Likely related to/duplicate of #447

**Comment by dakra** [comment] 2018-06-29 06:28
And related and the origin of the changes is from https://github.com/ch11ng/exwm/issues/435

**Comment by agzam** [comment] 2018-07-02 21:30
I did stumble upon that and it freaked me out. Surprisingly initially it was working fine (I just reinstalled my whole system), but suddenly it stopped. Apps basically won't respond to any Emacs keys - `C-c` won't work, simulation keys, etc.. Had to revert back as described in the issue. And now it works again. Hope it won't break now

**Comment by ch11ng** [comment] 2018-07-03 03:39
Sorry but I'm on a weeks-long business trip.  I'll investigate this when I get back perhaps next week.

**Comment by agzam** [comment] 2018-07-03 05:57
@ch11ng No need to apologize. We all know what it takes to maintain an open-source project. From the bottom of my heart thank you for all the amazing work. I can't imagine my life without this thing anymore. It gives me enormous amount of joy. And my workflow has become so incredibly empowering. I hope it becomes more popular. Emacs is great! Emacs as your window manager is simply fantastic!

**Comment by DamienCassou** [comment] 2018-07-03 06:32
That's exactly how I feel too @agzam! Thank you so much @ch11ng.

**Comment by ch11ng** [comment] 2018-07-15 11:19
This has been fixed with the latest code.

**Closed by ch11ng** 2018-07-15 11:19 UTC

**Comment by DamienCassou** [comment] 2018-07-15 15:36
Awesome. Thank you.
