### ISSUE TITLE
Issues with X applications not responding

### ISSUE THREAD

**Issue by wacossusca34** [ch11ng/exwm#154] opened 2016-04-10 20:15 UTC
Related to #82, two related (but hard to reproduce) issues:

- Applications that have not been traditionally closed (ie. sent `SIGKILL`) may be left with a dead buffer for the X windows associated with that application and will cause various issues, sometimes hanging EXWM and preventing keyboard/mouse input.

- Sometimes EXWM thinks an application is not responding, but the application remains completely usable (happens often with firefox), prompting to end the process every once in a while.

I am having other issues with EXWM that cause everything to lock up (sometimes pining out one of my cores at 100% in htop when I drop to a tty), but I am having a hard time finding ways to reproduce these issues.

**Comment by ch11ng** [comment] 2016-04-11 05:30
> Applications that have not been traditionally closed (ie. sent SIGKILL) may be left with a dead buffer for the X windows associated with that application and will cause various issues, sometimes hanging EXWM and preventing keyboard/mouse input.

I think it's because the connection to the X server encounters some problem.
It may not necessarily relate to how you close the application, so this bug is hard to trace.

> Sometimes EXWM thinks an application is not responding, but the application remains completely usable (happens often with firefox), prompting to end the process every once in a while.

The prompt appears only when you try to kill a buffer (see hook `kill-buffer-query-functions`).
I'll try firefox and see if I can reproduce this one.

> I am having other issues with EXWM that cause everything to lock up (sometimes pining out one of my cores at 100% in htop when I drop to a tty), but I am having a hard time finding ways to reproduce these issues.

You can send Emacs USR2 signal when it get stuck and it will enter the debugger.

**Comment by c256** [comment] 2016-04-11 15:38
Here's a longstanding bug in GTK that you might be seeing here.  Emacs has been running into this bug (GTK has decided wontfix, basically) for a long time. 

http://bugzilla.gnome.org/show_bug.cgi?id=85715

~Chad

**Comment by ch11ng** [comment] 2016-04-12 11:04
Hi @c256, what does the GTK bug have to do with these issues here?

**Comment by c256** [comment] 2016-04-15 01:59
Your comment about "the connection to the X server encounters some problem"
reminded me of the GTK issue, and my computer is in for repairs, so I
couldn't check closely myself. Sorry if it's just noise.

Thanks,
~Chad

**Comment by ch11ng** [comment] 2016-09-25 12:11
The first issue reported should be fixed by 7fbd5220f2e92059ad38776a3f8c674002396870.  As for the second one, I think there must be some code trying to kill that buffer, but the code may or may not be part of EXWM.  I used to experience it but not in the past few months.  I'm closing this issue now.  Please reopen it if you can confirm the issue persists.

**Closed by ch11ng** 2016-09-25 12:11 UTC
