### ISSUE TITLE
The update focus timer introduces a significant input lag

### ISSUE THREAD

**Issue by Stebalien** [ch11ng/exwm#310] opened 2017-10-13 20:32 UTC
To test, open a scratch buffer, repeatedly type the same character (e.g., 400 x 'a'), then use the arrow keys to move the cursor back and forth over the 'a's. With `exwm-input--update-focus-interval` set to the default value (0.01) the cursor stutters as it's moved over the text. With this value set to, e.g., 1, the cursor moves smoothly. This is a contrived example but there has to be a better way to do this than to poll every 0.01 seconds (i.e., use a separate process/thread?).

**Comment by ch11ng** [comment] 2017-10-15 13:39
This is perhaps the trickiest code in EXWM, and it might be the cause of many input focus issues.  The delay is likely hardware dependent.  You can fine-tune it to a small working value, but one second is definitely too long.

I wasn't able to reproduce your problem.  And I've tried your PR but it caused input focus loss for me.  The point here is not polling but deferring; the whole thing is triggered by `buffer-list-update-hook` which shouldn't be run simply by moving the cursor.  I suggest you try with a minimal configuration.

Running EXWM in another thread/process is of course reasonable, but I have no working design yet.

**Comment by Stebalien** [comment] 2017-10-15 17:36
Ah. Got it. There's a chance that some change to recent emacs-git made this worse as I've only just started to notice it.

Debugging this a bit more, it appears that `exwm-input--update-focus-defer` is getting triggered *every* keypress. I'll look into what's doing that.

**Comment by Stebalien** [comment] 2017-10-15 17:50
Found it. `format-spec` creates a new temporary buffer (in the latest emacs git at least). I can fix the immediate problem (spacemacs formatting the title) however, I expect this will still be called quite often.

**Comment by ch11ng** [comment] 2017-10-22 16:22
The code for `format-spec` is almost a decade old.  Perhaps there is something to do with how it get called? At least `exwm-input--update-focus-defer` won't get triggered when a normal temporary buffer is created or killed as these events are filtered out.

**Comment by Stebalien** [comment] 2017-10-22 16:42
Where do those events get filtered? It was being called from within `frame-title-format`.

**Comment by ch11ng** [comment] 2017-10-29 17:06
It's in `exwm-input--on-buffer-list-update`.  It filters those events out by detecting whether the focused buffer is current.

With EXWM making all frames full screen, setting `frame-title-format` is of no use BTW.

**Comment by Stebalien** [comment] 2017-10-29 17:24
> With EXWM making all frames full screen, setting frame-title-format is of no use BTW.

Yeah, I disabled it and the situation got *much* better.

>  It filters those events out by detecting whether the focused buffer is current.

Hm. Looks like a bug in Emacs 27 then then. I'll play around with it when I get time. Thanks.

**Comment by Stebalien** [comment] 2017-10-29 17:27
Actually, I wonder if both `window-buffer` and `current-buffer` are `nil` in this context...

**Comment by ch11ng** [comment] 2017-10-29 17:32
I think there's always a current buffer.

**Comment by Stebalien** [comment] 2017-10-29 17:34
Yeah. That's not the problem. It looks like the problem is that exwm filers the event where the temp buffer gains focus but *not* the event when the non-temp buffer re-gains focus. It may need to keep a last-focused-buffer variable or something like that.

**Comment by ch11ng** [comment] 2017-11-05 14:38
I've pushed a fix for this (dea874e240896762183e90d9aecb38ff95bbc62f).  You may try inserting a message into `exwm-input--update-focus` and see if it's called too frequently.

**Comment by Stebalien** [comment] 2017-11-10 18:50
So, now something is flip-flopping the current buffer multiple times a second (when focusing on an emacs buffer). Any tips on how to figure out what? It looks related to switching buffer focus (I can get this behavior to go away by messing with the `exwm-input--on-buffer-list-update` function enough).

As for that fix, I'm not sure if checking for the *existence* of a temp buffer is the correct fix (also, temp buffers will often have numbers appended to them). The problem here isn't when the temporary buffer is focused, it's when the original buffer regains focus.

I've tried fixing this as follows but it doesn't handle focus changes between EXWM windows (although it *does* print out the focus changes):

```elisp
(defvar exwm-input--update-focus-window nil "The (Emacs) window to be focused.

This value should always be overwritten.")

(defvar exwm-input--update-focus-buffer nil "The (Emacs) buffer to be focused.

This value should always be overwritten.")

(defun exwm-input--on-buffer-list-update ()
  "Run in `buffer-list-update-hook' to track input focus."
  (when (and (not (eq this-command #'handle-switch-frame))
             (not (exwm-workspace--client-p))
             ;; The following conditions filter out events relating to temp
             ;; buffers.
             (eq (current-buffer) (window-buffer))
             (not (eq (current-buffer) exwm-input--update-focus-buffer))) ; The new check
    (message "%S" (current-buffer)) ; This prints out for every buffer switch (EXWM/Emacs)
    (setq exwm-input--update-focus-window (selected-window)
          exwm-input--update-focus-buffer (current-buffer))
    (exwm-input--update-focus-defer)))
```

**Comment by Stebalien** [comment] 2017-11-10 19:16
Note: I *can* make this "work" by *not* not doing this extra check if the buffer is an exwm buffer (although it will then print out that it's switching to/from EXWM buffers *multiple* times instead of only once).

**Comment by ch11ng** [comment] 2017-11-12 18:37
There is clearly a regression in Emacs 26 I suppose is somewhat related to this issue.  I'm still investigating it.  As for the problem with temp buffer, I think I've got a solution.  I'll test and push them together.

**Comment by Stebalien** [comment] 2017-11-14 00:13
> There is clearly a regression in Emacs 26 I suppose is somewhat related to this issue.

Maybe. Something has definitely changed but this looks like recursion (buffer change -> exwm stuff -> buffer change, etc...). IMO, it's up to exwm to detect that recursion and stop it.

**Comment by ch11ng** [comment] 2017-11-19 07:25
It turns out to be https://github.com/emacs-mirror/emacs/commit/421c0512f76683e0b85ea5e1362291c2da4149ba that "breaks" EXWM.  It introduces a frame redirection when Emacs has no input focus.  I've push 71a39840b239a51eed7455877517ebe612892eff to fix this.  The commit also corrects the detection of temp buffer.  Please give it a try.

**Comment by Stebalien** [comment] 2017-11-19 23:33
That appears to fix it, I'm not seeing the issue anymore.

Note: I'm still seeing one additional update per X window switch (when switching form X buffer A to emacs buffer B, EXWM processes an additional focus of buffer A before focusing buffer B) but that's not really much of an issue.

---

However, I'm now seeing two fresh new bugs (hail hydra): #330, #331

**Closed** 2017-11-19 23:33 UTC
