### ISSUE TITLE
Some EXWM system tray icons do not update properly or show up initially

### ISSUE THREAD

**Issue by vedvyas** [ch11ng/exwm#183] opened 2016-08-06 17:57 UTC
The most consistently reproducible cases for me are:
1. [alarm-clock-applet](http://alarm-clock.pseudoberries.com/) - when an alarm fires, the tray icon should blink but instead just disappears. It is still possible to left- and right-click on the blank space where the icon was. Also, there is some minor flickering in other tray icons until the alarm is stopped.
2. mate-volume-control-applet - when decreasing the volume using the slider or scroll wheel down, the icon should decrease in size. This happens but you see the successively smaller versions painted on top of the larger ones.

Not as reproducible: Firefox and Thunderbird with the [FireTray](https://foudfou.github.io/FireTray/) add-on. Sometimes the tray icon does not show on FF/Tbird startup. Subsequently starting another program with a tray icon may cause the FireTray icon(s) to then show up. EDIT: I forgot to add that toggling the FireTray option "Show tray icon only if a window is hidden" can also cause the tray icon to (re)appear.

Setup: EXWM 0.8 + XELB 0.10 on Emacs 25.0.94.1. I have a timer that fires `exwm-systemtray--refresh` every 10s to mitigate some of these issues.

**Comment by ch11ng** [comment] 2016-08-07 05:40
I think these issues are probably the same with #184, at least for the second one.  Please report if the problems are resolved by 06c1b0485a1815d13ded7bd717adf5d9735be3df.

**Comment by vedvyas** [comment] 2016-08-07 17:01
Thank you, I can confirm that the volume-control-applet problem is resolved by 06c1b04. FireTray is looking good so far as well. alarm-clock-applet still disappears.

**Comment by ch11ng** [comment] 2016-08-08 14:40
> alarm-clock-applet still disappears

I've tested version 0.3.4 down to 0.3.0 and cannot reproduce it.  The tray icon in higher versions doesn't seem to blink by itself, while icon in lower versions blinks normally.

**Comment by vedvyas** [comment] 2016-08-08 17:10
Interesting, thank you for trying that. I use 0.3.4, built from source against GTK+ 2.24.28. It changes to the expected yellow, blinking icon when I use it in a regular MATE session.

Looking at the code, the GTK function `gtk_status_icon_set_blinking` is used to blink the icon (src/ui.c:330). This function is apparently deprecated. I commented out the call to it in ui.c and rebuilt. Now the icon changes to the yellow "triggered" icon and doesn't disappear, but the initial tray icon sometimes fails to show up when starting alarm-clock-applet. That's unfortunate :)

It may not be worth it to spend further time on alarm-clock-applet specifically. If you agree, I'd be OK with closing this issue for now.

**Comment by ch11ng** [comment] 2016-08-09 05:59
> the initial tray icon sometimes fails to show up when starting alarm-clock-applet

You may try setting `exwm-systemtray-height` to some typical values like 16 or 32.  Some applets may have problem with other sizes.

> It may not be worth it to spend further time on alarm-clock-applet specifically. If you agree, I'd be OK with closing this issue for now.

All right.

**Closed by ch11ng** 2016-08-09 05:59 UTC

**Comment by vedvyas** [comment] 2016-08-09 14:47
I will try that, thanks again!
