### ISSUE TITLE
Windmove and input-set-key

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#235] opened 2017-03-20 01:55 UTC
I've been using windmove to move around my buffers fast using s-left, right, up, down and it's been great, but if I have a GUI app open like a browser then it doesn't work and I have to use the `C-x o` emacs command to move buffers.

Is it possible to set such a key combination?:

    (exwm-input-set-key (kbd "s-<right>") 'windmove-right)

I found that I could set some keys using exwm-input-set-key but not all, is it possible to get a list of available keys for use with exwm, or is this a bug and I should be able to set any key combination I want?

**Comment by jtamagnan** [comment] 2017-03-20 18:37
Does adding something like? `(push (elt (kbd "s-<right>") 0) exwm-input-prefix-keys)` help? This will not bind the key but will allow it to be passed through to emacs through exwm (There might be a cleaner way to do this but it works for me)

**Comment by map7** [comment] 2017-03-21 22:04
Yes this works, thank you for the work around.

**Comment by jtamagnan** [comment] 2017-03-24 19:57
If your issue is resolved maybe it would be best to close this issue?

**Closed** 2017-03-27 23:10 UTC

**Comment by ch11ng** [comment] 2017-04-03 07:05
It shouldn't be necessary to modify `exwm-input-prefix-keys` for a keybinding set with `exwm-input-set-key`.  Note that you should put `exwm-input-set-key` in your `.emacs` or invoke it interactively via <kbd>M-x exwm-input-set-key</kbd>.

**Comment by map7** [comment] 2017-04-03 23:16
I have put the following in my .emacs.d/custom/exwm.el file which I import within my .emacs.d/init.el

```
(exwm-input-set-key (kbd "s-<right>") 'windmove-right)
(push (elt (kbd "s-<right>") 0) exwm-input-prefix-keys)
```

Without the prefix-keys line it doesn't work.

I have found that setting some keys with exwm-input-set-key work and others don't and have to be forced.

Here are the keys I have working;

```
(exwm-input-set-key (kbd "s-l")
                    (lambda () (interactive)
                      (start-process "" nil "slock")
                      (start-process "" nil "sudo" "pm-suspend")))

;; Redshift off
(exwm-input-set-key (kbd "s-x")
                    (lambda () (interactive) (start-process "" nil "redshift" "-x" )))

;; Redshift on
(exwm-input-set-key (kbd "s-z")
                    (lambda () (interactive) (start-process "" nil "redshift" "-O" "3500")))

;; Turn on capslock
(exwm-input-set-key (kbd "s-c")
                    (lambda () (interactive) (start-process "" nil "setxkbmap" "-layout" "us" "-option" "ctrl:nocaps")))

;; Suspend nicely
(exwm-input-set-key (kbd "s-<f12>")
                    (lambda () (interactive) (start-process "" nil "sudo" "pm-suspend")))


```

**Comment by ch11ng** [comment] 2017-04-09 16:17
Does manually run `exwm-input--update-global-prefix-keys` works? How and when is `.emacs.d/custom/exwm.el` imported?

**Comment by map7** [comment] 2017-05-24 23:47
If I run exwm-input--update-global-prefix-keys I get an error. I load the .emacs.d/custom/exwm.el last in my setup. My full setup is github.com/map7/emacs-config

**Comment by ch11ng** [comment] 2017-05-29 17:39
Where did `exwm-input--update-global-prefix-keys` get called and what was the error? This is a normal function and should run correctly when EXWM is fully initialized.

**Comment by Ambrevar** [comment] 2018-01-19 14:21
I tried binding "s-<arrows>" as the original post mentioned.
I could repoduce the issue and calling `(exwm-input--update-global-prefix-keys)` did the trick.

@ch11ng: Could you explain why this is necessary?
Since this is rather misleading, would it be possible to make EXWM support these out of the box?
If not, I'll update the wiki.

**Comment by ch11ng** [comment] 2018-01-21 12:41
There may be some problems in translating Emacs modifiers to X ones.  Please upgrade XELB and see if EXWM reports something like 'Failed to grab key'.  With older versions of XELB unrecognized modifiers are simply ignored so <kbd>s-a</kbd> would simply be treated as <kbd>a</kbd> when <kbd>super</kbd> is not defined which is definitely unwanted.

**Comment by Ambrevar** [comment] 2018-01-23 09:26
Weird, I'm not able to reproduce now...

**Comment by Francesco149** [comment] 2018-03-08 10:40
I had the same issue binding keys involving ctrl + shift and running ```exwm-input--update-global-prefix-keys``` fixed the issue

```
(exwm-input-set-key (kbd "C-@") #'sharenix-full)
(exwm-input-set-key (kbd "C-#") #'sharenix-window)
(exwm-input-set-key (kbd "C-$") #'sharenix-section)
(exwm-input-set-key (kbd "C-%") #'sharenix-clipboard)
```

**Comment by ch11ng** [comment] 2018-03-08 17:14
@Francesco149 Is the variable `exwm-input--global-prefix-keys` updated after you run `exwm-input--update-global-prefix-keys`?

**Comment by Francesco149** [comment] 2018-03-08 20:08
ah yes my bad, I didn't even check my versions

running exwm 0.16 and xelb 0.12

I'll update to latest and re-test

**Comment by Francesco149** [comment] 2018-03-08 20:21
works perfectly on latest version, sorry for the false alarm :ok_hand:
