### ISSUE TITLE
problems with prefix-keys and char-mode

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#109] opened 2016-02-07 06:37 UTC
Problem: 

reservating keys for exwm with:
```elisp
(push 'menu exwm-input-prefix-keys)
(push 'XF86Launch5 exwm-input-prefix-keys)
```

deos not work anymore, I am not shure it still works when I am in line-mode but in charmode it does not work, I think I used conkeror in line-mode before so that was no problem, but in 0.1 exwm then I can type stuff into textboxes, or it was startet automaticly in charmode.

So basicly I have 2 problems 

1.it seems I neet to start buffers automaticly in charmode, or at least some buffers like in this case conkeror.
2. I need a way to define that prefix keys so that emacs gets this keys not the stupid browser :)

I seen a related bug I guess, but it 1. does not tell how to automaticly start conkeror in charmode, and the solution seems to not work for me, or I used it wrong:

```elisp
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (when (and exwm-class-name
                       (string= exwm-class-name "Conkeror"))
              (make-variable-buffer-local 'exwm-input-prefix-keys)
              (setq exwm-input-prefix-keys '(menu)))))
```

both "solutions do not work for me anymore, the push statements worked in 0.1 so I see that as regression, but maybe its a feature :)

**Comment by ch11ng** [comment] 2016-02-07 07:08
Something to clarify:

* `exwm-mode` buffers are always started in `line-mode`.
* `exwm-input-prefix-keys` only works in `line-mode`.

I've just tried and it works.  I think what you need is still `line-mode` since you want the key get sent to Emacs.

**Comment by spiderbit** [comment] 2016-02-07 13:43
but linemode does not work with conkeror now, it did with exwm 0.1 I cant type in stuff in textfields it all gets recognised as commands now. so I have as example setup g to "u" to find-url-in-buffer, in charmode an in 0.1 also in linemode, that got not executed when I am in a text-buffer instead the letter "u" was send to the text-field.

its like line-mode activates now a command-mode in conkeror. I find that interesting to be honest, but on the other hand I wonder if that was the idea, as example when I open urxvt I can type text in in line-mode. So it seems more to be a bug, then a feature.

**Comment by spiderbit** [comment] 2016-02-08 00:10
I did bisect hunt down the regression the commit that intertruced it was:
9c95c03

before that commit conkeror just worked fine in line mode, after it I have to change to char-mode to write stuff in this or any other formular. 

so basicly the bug/regression is that conkeror does not work fully in line-mode.

**Comment by ch11ng** [comment] 2016-02-08 02:23
I don't think I can reproduce it here.  It sounds to me like that you can't even type text with the text field selected.  How about cleaning up your configurations (both EXWM and Conkeror) and testing the default key bindings (e.g. `g`)?

**Comment by spiderbit** [comment] 2016-02-08 03:12
the keybindings work, the textfields not, so if I am in a textfield, ant start to type as example g it starts the command instead of putting the letter in there.

Another thing somebody other mentioned that he need char-mode for conkeror, and pretty much had the same problem, his workaround does not work here. Maybe I have to escape my keys different for that.

But it should not be the point of finding or adapting new workarounds but fixing problems right? I find you the bugreport I mean and post it here.

**Comment by ch11ng** [comment] 2016-02-08 03:33
So after you press a command key, does the text field lost focus? What about other non-command keys?

> he describes that he needs charmode for his browser conkeror. so it seems he run into the same problem I have.

I think he meant Emacs and Conkeror have similar key bindings so `char-mode` is necessary to resolve the conflict.

**Comment by spiderbit** [comment] 2016-02-08 03:42
maybe, they are configurable both, so I dont really get it, but maybe you are right.

just testet something and I didnt want to belive it, but conkeror without a config file works.

so basicly a mulitfactor bug, a "wrong" conkerorrc and a newer version of exwm that leads to that behaviour.

that said when I type stuff now into a texbox it wirdly blinks all 10 chars or so. like it would loose focus. but that would be at best a minor issue :)

so ok I will hunt tomorow down which settings in my conkeror-config file causes this problem, and report back, maybe we can then figure out what the problem is.

**Comment by spiderbit** [comment] 2016-02-08 04:14
k found it.
still funny that this problem did not occur with older version of exwm:

http://conkeror.org/Focus

that line /modus causes the problem. its basicly a prevention, that websites dont steel focus and jump into a text field. that way I am in command mode by default.

`require("block-content-focus-change.js");`

**Comment by ch11ng** [comment] 2016-02-08 04:32
The input focus model is changed since that commit.  It should be more stable now.  What about the blinking problem you mentioned?

**Comment by spiderbit** [comment] 2016-02-08 06:00
more stable does that mean less crashes? I cant really blaim exwm for that but somethimes it crashes.

the blinking I so far see only here on github, tthere a holo effekt a blue one around this boxes, and it goes off and on it has to do with how fast I type, when I type slower it does not flash, but I dont need to write superfast.

ahh now I seen it, its when emacs blocks instead of pasting it it flashes. but I think I saw it even with gnus off, dont know if its worth fixing I cant even really say if its a new bug. And at least for today I have enough exwm restarting and git resetting behind me :)

**Comment by ch11ng** [comment] 2016-02-08 06:14
When saying 'more stable' I mean the input focus only.  It does crash Emacs sometimes though.

I really suspect the blinking issue since I cannot reproduce it here.  Maybe you still have something misconfigured? Please test with the default configuration file.

**Comment by ch11ng** [comment] 2016-02-19 13:10
I'm closing this issue now.  If you're still experiencing the blinking problem please open a new one.

**Closed by ch11ng** 2016-02-19 13:10 UTC
