### ISSUE TITLE
Telegram doesn't work with exwm-xim

### ISSUE THREAD

**Issue by TatriX** [ch11ng/exwm#632] opened 2019-08-27 08:16 UTC
Probably not a exwm issue, but still.
So I'm using `exwm-xim` with
```
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim
```
and it works for all applications I use except for `telegram-desktop`.
I think I've tried any advice on the topic from their repo and still no luck - telegram ignores everything and only emits English letters.

I wonder if anybody managed to make it work?

**Comment by TatriX** [comment] 2019-08-27 08:49
Also I've just found that java app [Netlogo](https://ccl.northwestern.edu/netlogo/) doesn't work with exwm-xim. It becomes fully unresponsive. Parts of the java stack traces:
```
   java.lang.Thread.State: RUNNABLE
	at sun.awt.X11.XInputMethod.openXIMNative(java.desktop@12.0.2/Native Method)
	at sun.awt.X11.XInputMethod.openXIM(java.desktop@12.0.2/XInputMethod.java:64)
	at sun.awt.X11InputMethodBase.initXIM(java.desktop@12.0.2/X11InputMethodBase.java:187)
	- locked <0x000000008c7c9070> (a sun.awt.X11.XInputMethod)
	at sun.awt.X11InputMethodBase.<init>(java.desktop@12.0.2/X11InputMethodBase.java:170)
	at sun.awt.X11InputMethod.<init>(java.desktop@12.0.2/X11InputMethod.java:51)
	at sun.awt.X11.XInputMethod.<init>(java.desktop@12.0.2/XInputMethod.java:49)
	at sun.awt.X11.XInputMethodDescriptor.createInputMethod(java.desktop@12.0.2/XInputMethodDescriptor.java:38)
	at sun.awt.im.InputContext.getInputMethodInstance(java.desktop@12.0.2/InputContext.java:855)
	at sun.awt.im.InputContext.getInputMethod(java.desktop@12.0.2/InputContext.java:805)
	- locked <0x0000000085f84f70> (a sun.awt.im.InputMethodContext)
	at sun.awt.im.InputContext.dispatchEvent(java.desktop@12.0.2/InputContext.java:240)
```

**Comment by ch11ng** [comment] 2019-09-01 08:42
This is because Telegram is a Qt5 application and Qt5 doesn't work with XIM.  There was an attempt (ch11ng/exim#6) to make this input method module work with Qt5 but we are not there yet.

> Also I've just found that java app Netlogo doesn't work with exwm-xim. It becomes fully unresponsive. Parts of the java stack traces:

It works for me, at least in `Interface > observer` and `Code` (version 6.1.0).

**Comment by WorldsEndless** [comment] 2019-09-04 11:55
I'm just using exwm vanilla and have been using Telegram Desktop heavily since the beginning, with no problems...

**Comment by ch11ng** [comment] 2019-09-08 06:43
@WorldsEndless What is your issue here? Without the `exwm-xim` module you can still use some other input method.

**Comment by TatriX** [comment] 2019-09-09 10:06
I switched to [telega](https://github.com/zevlg/telega.el) and it's pretty good. Not a real solution to the root cause of course.

**Comment by WorldsEndless** [comment] 2019-09-09 12:24
> @WorldsEndless What is your issue here? Without the `exwm-xim` module you can still use some other input method.

Sorry -- my point was that I have no issue and cannot confirm. The Telegram client works marvelously (as an aside, I did not like Telega with exwm, because all it's blocking requests hurt the whole system).

**Comment by zevlg** [comment] 2019-09-09 12:34
> > @WorldsEndless What is your issue here? Without the `exwm-xim` module you can still use some other input method.
> 
> Sorry -- my point was that I have no issue and cannot confirm. The Telegram client works marvelously (as an aside, I did not like Telega with exwm, because all it's blocking requests hurt the whole system).

hmm, I'm using [telega](https://github.com/zevlg/telega.el) in exwm environment for quite long time.  Could you please create issue in telega repo to discuss the problem in more details, thanks

**Comment by WorldsEndless** [comment] 2019-09-09 15:45
@zevlg I am not the OP. My point is simply that I cannot reproduce his problem. I have no issue to create.

**Comment by WorldsEndless** [comment] 2020-05-28 12:28
Can we close this issue?

**Closed** 2020-05-28 12:55 UTC
