### ISSUE TITLE
Problem with dialog window opened by main emacs instance

### ISSUE THREAD

**Issue by mgudemann** [ch11ng/exwm#46] opened 2015-08-25 15:59 UTC
Hi,

my problem is that I often use `M-x menu-set-font` which normally opens a dialog window to select a font and font-size for emacs; unfortunately this does not work when using in the main emacs instance running for exwm. Do you have any pointers how to resolve this?

Best regards,
Matthias

**Comment by pipcet** [comment] 2015-08-25 20:36
In summary, this is a difficult issue and probably will never be fully fixed in upstream Emacs. But at least I can confirm it's real.

@ch11ng is likely to have something more cogent to say, but I have looked into this briefly and would like to share what I found:

The problem is Emacs (the main parts, at least) is single-threaded. The same thread runs the window manager and GTK, so when GTK sits in a loop waiting for the window manager to do something, nothing ever happens.

(Maybe one day Emacs will become multi-threaded, but there are very good reasons for that not to be done today.)

The GTK loop is considerate enough to run Emacs timers, but not to run mode line updates or accept process output. For example, I use (display-time-mode) to display the time in the mode line, and that doesn't get updated while the GTK dialog is open. Obviously, that's a much less severe issue than being unable to use the dialog, but it's the same underlying problem.

There are several options:
 (1) disable X dialogs when EXWM is active
 (2) trick GTK into doing the right thing with some clever Lisp code
 (3) fix Emacs

(1) is the most attractive option for now, but in the long term it's a bad choice. (2) is really, really hard, and I haven't even worked out whether it's possible. (3) is surprisingly easy:

 - set up a temporary keymap binding C-g to (throw 'exit nil)
 - call Frecursive_edit() rather than g_run_main_loop
 - when you've got a response, simulate a C-g keypress and stuff it in the keyboard buffer.

Note that we cannot get away with just throwing in the event handler, that leaves GTK in an inconsistent state.

If you want to build your own Emacs, you can play with the code (which is far from perfect) by checking out https://github.com/emacs-mirror/emacs/compare/master...pipcet:fix-gtk-dialog?expand=1 and https://github.com/ch11ng/exwm/compare/master...pipcet:fix-gtk-dialog?expand=1 (you have to apply both of them together, not just one); however, I must warn you that since I might be introducing race conditions, there's a small but real disk of data corruption. You might want to back up before trying the changed versions.

As I said, it's far from perfect (repeated dialogs can only be confirmed with the mouse, not the keyboard), but surprisingly it seems to work. If you do test (or even improve) the changes, please let me know how it works out!

Sorry this got a bit long.

**Comment by ch11ng** [comment] 2015-08-26 01:46
I'm not a GTK guru so I'd follow what @pipcet had said. There is no easy workaround since this dialog cannot be disabled. One weird thing is that even with `(exwm--lock)` this dialog won't show up; it's created but not mapped in any case. There is an alternative called `mouse-select-font` but it does not work either (it partly works on Lucid build; you can pick fonts though the top-level menu is invisible). I think we should get this dialog mapped at least, though it's unlikely that we are able to make it managed as a normal window.

**Comment by mgudemann** [comment] 2015-08-26 06:39
Hi @pipcet and @ch11ng ,

thanks for the answer. I'll have a look at building emacs my own with your suggestions. This is no show stopper, I was just wondering whether I had missed something.

**Comment by ch11ng** [comment] 2015-09-27 11:47
Fixed in 5184f0d7c1b540a6241904528d068dce288a911e, but the use of it should still be discouraged.

**Closed by ch11ng** 2015-09-27 11:47 UTC

**Comment by mgudemann** [comment] 2015-10-05 06:46
I confirm it works, although keyboard input doesn't. 

Shouldn't we remove 
```
;; Disable dialog boxes since they are unusable in EXWM
(setq use-dialog-box nil)
```
from the example config, then?

**Comment by ch11ng** [comment] 2015-10-05 07:37
The support is still very limited because those dialog windows cannot be manged. So let's keep this setting for now.
