### ISSUE TITLE
Floating windows bugs

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#156] opened 2016-04-19 08:48 UTC
I've run into two new bugs with floating windows in the current master.

1. Firefox
When closing firefox with multiple tabs, the 
```You are about to close X tabs, are you sure..``` window has wrong proportions such that the OK/Cancel buttons are not visible.

2. Nautilus
Rightclicking file and choosing ```Properties``` or ```Rename```, rightclicking blank space and choosing ```Create folder``` etc. does not spawn floating window, makes Nautilus freeze and it must be killed. I am very sure this is caused by some new commit, I would notice it otherwise.

**Comment by ch11ng** [comment] 2016-04-20 13:00
> When closing firefox with multiple tabs, the 
`You are about to close X tabs, are you sure..` window has wrong proportions such that the OK/Cancel buttons are not visible.

Yes I can confirm this.  Actually firefox requests so small a size, maybe because EXWM does not resize the floating X window precisely.  It seems we have to rethink the code concerning floating X windows.

> Rightclicking file and choosing `Properties` or `Rename`, rightclicking blank space and choosing `Create folder` etc. does not spawn floating window, makes Nautilus freeze and it must be killed. I am very sure this is caused by some new commit, I would notice it otherwise.

I cannot reproduce this one though (the version is 3.20.0); those X windows would appear undecorated.

**Comment by fm4d** [comment] 2016-04-20 13:50
> I cannot reproduce this one though (the version is 3.20.0); those X windows would appear undecorated.

It seems like it only happens on external displays, on the primary it also works well for me.

**Comment by fm4d** [comment] 2016-04-20 18:23
The bug #1 can be also seen in Deluge (for example rightclick torrent and choose ```Move storage```, ```Remove torrent``` or ```Help->About```)

**Comment by ch11ng** [comment] 2016-04-21 11:33
I've fixed the second one in 367bdf2e1918dd61780e2284a4c89d5ef8cd1254.

**Comment by fm4d** [comment] 2016-04-27 08:38
Another bug similar to #2 in Deluge v. 1.3.12.
Steps:
1. ```File -> Add Torrent```
2. Press ```File```
The filesystem navigation window should be very tiny, unusable (on both primary/external display).
Clicking outside this window => it dissapears and Deluge freeze.

**Comment by carbohydratesn** [comment] 2016-04-30 18:20
Hey, I'm having similar problems.

When the main emacs window is split into two or more buffers, new floating windows look like this - 

![2016-04-30-120849_1366x768_scrot](https://cloud.githubusercontent.com/assets/8284150/14937713/25d06612-0ecd-11e6-87e2-925e05c0b30f.png)

- strange and blue.  

With one buffer visible in the main emacs window, new floating windows usually work normally, but other times, they are too small, especially after experiencing the above problem.

**Comment by ch11ng** [comment] 2016-05-03 11:41
Sorry for the delay.

@fm4d, what you reported is the same as the first issue where the floating X windows are wrongly resized.  As for the freezing problem, I think you clicked another floating X window (likely the one popped up after you clicked `Add Torrent`).  If this is the case, you should switch to that buffer or move away the floating X window on the top.

@carbohydratesn, can the problems you reported be reproduced reliably? I don't have spacemacs installed so I cannot verify it.  But based on your description, the first problem was due to some packages emitting warnings/errors and you should be able to find the messages if you scrolled down the buffer displayed in the blue window.  The warning message in the second problem was from `persp-mode` and as it said it was because the floating X window was too small (maybe it's also wrongly resized).

**Comment by fm4d** [comment] 2016-05-04 11:42
Ok then, from my point of view it looked like two different issues (they were slight differences, for example the Firefox window was actually first displayed well and after ~1 second it was wrongly resized, but the Deluge window was already spawned small). BTW what is the status of this bug? There is no easy fix?

**Comment by ch11ng** [comment] 2016-05-05 05:38
@fm4d, I once thought the problem was due to f0a5425f4c176c487a5c3e94319f0c2b3d3cc22a but reverting to earlier commits does not fix it.  Indeed I noticed some floating X windows (including Firefox) were created very small and apparently that's abnormal, however I'm not sure what's going wrong.  I can't tell whether there's a easy fix before I find the reason behind the problem.  I tend to believe the different issues you mentioned here are actually the same.

**Comment by carbohydratesn** [comment] 2016-05-07 14:56
(I think) from helm and scrot@ch11ng, it can be reproduced 100% of the time, on both of my computers - C-x 3, then do anything that creates a floating window.

The buffer displayed in the blue window is just a mirror of whatever's below it, it duplicates the content of *Messages* if that buffer is open.  The errors were either from Slime or my first attempt at running scrot, there were none created when the floating window was created.

**Comment by ch11ng** [comment] 2016-05-10 15:56
@carbohydratesn,

> The errors were either from Slime or my first attempt at running scrot, there were none created when the floating window was created.

Which errors did you refer to? And what about the `persp-mode` warning you mentioned last time?

**Comment by carbohydratesn** [comment] 2016-05-11 05:05
"But based on your description, the first problem was due to some packages emitting warnings/errors and you should be able to find the messages"

Those errors were simply in my *Messages* buffer, none are generated when this happens.  


The persp-mode error only occurs when a floating window tries to split itself vertically upon creation, C-x 2 style.  The desired window is created properly, so I can only imagine that it is failing to create the faulty split.  That is where the persp-mode error comes from, it seems to be trying to 'restore' the configuration of the window under it.

And hey, eureka.  I am dumb.  persp-mode is 'restoring' layouts onto new windows.  This is a persp-mode-interacting-with-EXWM issue, not EXWM!  Please disregard all that :P  I will make the necessary changes to my spacemacs/exwm config.

**Comment by ch11ng** [comment] 2016-05-11 11:02
@carbohydratesn,

> And hey, eureka. I am dumb. persp-mode is 'restoring' layouts onto new windows. This is a persp-mode-interacting-with-EXWM issue, not EXWM! Please disregard all that :P I will make the necessary changes to my spacemacs/exwm config.

Well this just explains everything except the original issue.

**Comment by ch11ng** [comment] 2016-05-17 05:46
This issue turns out to be a bug of Emacs itself (see https://debbugs.gnu.org/db/23/23144.html), which is now fixed in the emacs-25 and master branch of Emacs.  I'm closing it now.  Please reopen it if you're still experiencing it with the latest build of Emacs.

**Closed by ch11ng** 2016-05-17 05:46 UTC

**Comment by agzam** [comment] 2018-05-14 01:53
It is indeed `persp` (AKA Layouts to Spacemacs users) thing, I set `(setq persp-init-frame-behaviour nil)` and things work fine now (I think)
