### ISSUE TITLE
Mouse events do not move / resize floating windows

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#283] opened 2017-07-27 11:08 UTC
Using `s-<down-mouse-1>` or `s-<down-mouse-3>` does not move/resize the floating windows.

The problem does not occur on an up-to-date Gentoo / Arch Linux.
It only happens on Ubuntu Trusty.  Maybe so because Xorg is out-of-date?

Some info:

```
> apt show xserver-xorg
Package: xserver-xorg
Priority: optional
Section: x11
Installed-Size: 375 kB
Maintainer: Ubuntu X-SWAT <ubuntu-x@lists.ubuntu.com>
Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Source: xorg
Version: 1:7.7+1ubuntu8.1
Replaces: xorg-renamed-package, xserver-xorg-renamed
Provides: xserver, xserver-xorg-renamed
Depends: xserver-xorg-core (>= 2:1.11), xserver-xorg-video-all (>= 0~) | xorg-driver-video, xserver-xorg-input-all (>= 0~) | xorg-driver-input, xserver-xorg-input-evdev (>= 0~), libc6 (>= 2.7), xkb-data (>= 1.4), x11-xkb-utils
...
```

```
In GNU Emacs 25.2.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)
 of 2017-06-28 built on sst-p1307278fl
Repository revision: 3a34412caae002accd0fc7a7fc0b718c2f34159b
Windowing system distributor 'The X.Org Foundation', version 11.0.11501000
System Description:	Ubuntu 14.04.2 LTS

Configured using:
 'configure --with-pop=yes --with-x-toolkit=gtk3'

Configured features:
XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
NOTIFY GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
TOOLKIT_SCROLL_BARS GTK3 X11
```

**Comment by ch11ng** [comment] 2017-07-30 17:43
What's the values of these variables: `exwm-input--move-keysym`, `exwm-input--move-mask`, `exwm-input--resize-keysym` and `exwm-input--resize-mask`? And does it solve the problem after you switch to char-mode and back to line-mode?

**Comment by Ambrevar** [comment] 2017-07-31 08:38
- `exwm-input--move-keysym` 1
- `exwm-input--move-mask` 64
- `exwm-input--resize-keysym` 3
- `exwm-input--resize-mask` 64

Changing to char-mode and back to line-mode does not solve the problem.

**Comment by mitch-kyle** [comment] 2017-08-06 20:24
I'm experiencing the same behavior. From what I can tell, the x window is eating the exwm keybinding

This how I tested it: (same behavior in char and line mode)

```elisp
;; 1.
(exwm-input-set-key (kbd "C-f") (lambda () (message "I ran")))
;; 2.
;; Start firefox and press 'C-f'

;; Expected: "I ran" message
;; Actual: firefox find in page dialog
```

I'm hoping this rings some bells but if not I'll keep digging for a root cause

**Comment by Ambrevar** [comment] 2017-08-07 08:44
In my case the window behaves the same floating or not regarding bindings. My `s-` prefixed bindings set with `exwm-input-set-key` work properly in line mode, while they are send to the program in char mode, as expected.

Only the mouse events seem to be affected.

**Comment by Ambrevar** [comment] 2017-08-07 08:48
Something else: If I bind
```
(exwm-input-set-key (kbd "s-<mouse-1>") (lambda () (interactive) (message "I ran")))
```
The binding will work in a non-EXWM buffer while it won't in an EXWM buffer. It seems that mouse bindings don't work on such a setup.

**Comment by ch11ng** [comment] 2017-08-13 05:57
EXWM should report `Failed to grab keyboard for #x...` if the pointer can not be grabbed.  Or you can check `exwm-input--on-ButtonPress` if EXWM receives the mouse events.

**Comment by Ambrevar** [comment] 2017-08-14 08:33
EXWM does not report anything.
`exwm-input--on-ButtonPress` is a function with `data` and `_synthetic` as arguments.  How do I use it?

**Comment by ch11ng** [comment] 2017-08-20 16:44
You can insert some `message` forms into the body of `exwm-input--on-ButtonPress` and see if there is any event received.  Since you said there was no error message I suppose EXWM managed to grab the pointer, and the only reason I can think of is the keysyms mismatch.

**Comment by Ambrevar** [comment] 2017-08-29 11:27
Indeed, the `cond` always goes for the "click to focus" part.
Some values:
- state=16
- detail=1

I am not familiar with the EXWM objects: any tip on how to debug from here?

**Comment by ch11ng** [comment] 2017-08-30 17:16
So when you did <kbd>super + click</kbd> XELB detected Mod2 while expecting Mod4.  Did you make any change to your keyboard mapping? Typically the output of xmodmap would look like this:

```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

**Comment by Ambrevar** [comment] 2017-09-04 08:06
```
/usr/bin/xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Shift_L (0x32)
control     Control_L (0x25),  Control_L (0x42),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3      
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

True, my keymap is modified:
- I use a custom XKB symbol map where Caps Lock is Ctrl and LShift+RShift is Caps Lock.
- I use xcape so that Ctrl sends Esc when not acting as a modifier: `xcape -e 'Control_L=Escape'`.

"super" keys should be fine though, as xmodmap outputs.

**Comment by Ambrevar** [comment] 2017-09-04 08:16
I just found what triggers the issue: when `numlock` is on!
If I press `numlock` I can move the window, otherwise I cannot.

I have no clue why as this does not make sense to me.  Any idea?

Note: Again, this issue only occurs on one of my machines running Ubuntu 14.04.

**Comment by ch11ng** [comment] 2017-09-10 10:29
This issue has been fixed in 75eb43e1e0a0e2efb7107ebed565abd40fdfd0c4.

**Closed by ch11ng** 2017-09-10 10:29 UTC

**Comment by jlagarespo** [comment] 2020-04-08 10:37
I seem to have a similar issue, though I do not have a num lock key in my keyboard.

**Comment by ch11ng** [comment] 2020-04-12 12:26
@jlagarespo Could you elaborate on that?

**Comment by jlagarespo** [comment] 2020-04-17 11:50
Using S-<down-mouse3> does seem to work indeed, it resizes windows, but S-<down-mouse-1> doesn't really move the window at all.

**Comment by ch11ng** [comment] 2020-05-05 12:31
When you said `S-<down-mouse-1>`, did you mean <kbd>super</kbd> or <kbd>shift</kbd> for the `S`?

This sounds like a different issue.  Could you carry out the checks as mentioned in https://github.com/ch11ng/exwm/issues/283#issuecomment-318917257 ?

**Comment by jlagarespo** [comment] 2020-05-06 13:27
Caps S is shift right? Because yeah, I meant shift.

**Comment by ch11ng** [comment] 2020-05-10 13:04
I see.  `S-<down-mouse-1>` should also work as I've tried, so it likely conflicts with some other setting on your system.  You can start by checking your Emacs configurations.  And if you run EXWM in some desktop environment, that key may not be accessible.
