### ISSUE TITLE
Floating windows with wrong proportions + crashes

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#112] opened 2016-02-15 19:57 UTC
It seems like update to version 0.2 (and XELB 0.5) totally broke floating windows for me.
1) Basically most floating windows are now spawn with wrong proportions, they are usually much bigger than intended and part of them is outside of screen.
![2016-02-15_20 00 21_1366x768_scrotum](https://cloud.githubusercontent.com/assets/6408638/13058757/968407ac-d425-11e5-97b9-2c5c16d9cb8f.png)
![2016-02-15_20 02 45_1366x768_scrotum](https://cloud.githubusercontent.com/assets/6408638/13058762/a14f3846-d425-11e5-9ac6-3448d0aa993a.png)
![2016-02-15_20 03 17_1366x768_scrotum](https://cloud.githubusercontent.com/assets/6408638/13058772/b0b9e2e0-d425-11e5-8941-be2ff9119d65.png)
![2016-02-15_20 06 18_1366x768_scrotum](https://cloud.githubusercontent.com/assets/6408638/13058775/b75b3bee-d425-11e5-8406-4e4752469342.png)
![2016-02-15_20 14 16_1366x768_scrotum](https://cloud.githubusercontent.com/assets/6408638/13058776/ba148142-d425-11e5-8c75-4b34ed899aff.png)

2) Floating windows are not spawned inside their mother window but like this:
![2016-02-15_20 02 59_1366x768_scrotum](https://cloud.githubusercontent.com/assets/6408638/13058770/a9f334de-d425-11e5-8591-51b1cebb7231.png)

3) When floating window is closed there is some chance (like 25%) that whole X Window session crash. I cannot find anything in logs and I have no precise way how to reproduce it but I believe that if you play a bit with floating windows in Deluge for example you will experience that crash too. Try adding torrents or so. EDIT: I have a way how to precisely reproduce it but it involves not a very common software - cherrytree http://www.giuspen.com/cherrytree/.

**Comment by ch11ng** [comment] 2016-02-16 02:11
I tried both Deluge and cherrytree, but I don't think I can reproduce these issues here.  Please try the default configuration and see if it works.

> 1) Basically most floating windows are now spawn with wrong proportions, they are usually much bigger than intended and part of them is outside of screen.

Please install EXWM from source and toggle the debug symbols on:

```elisp
(setq debug-on-error t)
(setq exwm-debug-on t)
```

Then the messages can tell something I think.

> 2) Floating windows are not spawned inside their mother window but like this

This is because the floating X window is too big.

> 3) When floating window is closed there is some chance (like 25%) that whole X Window session crash

How the floating X window was closed? By killing the buffer or clicking some buttons?

**Comment by fm4d** [comment] 2016-02-16 09:04
The floating X windows were closed by clicking buttons in standart way.
Update: commenting out this `(add-hook 'exwm-floating-setup-hook (lambda () (exwm-floating-hide-mode-line)))` fixed the enlarged windows for me because it looks like exwm first spawns the window with some default size (as can be seen on screenshots - all windows have same proportions) and then they are resized and that hide-mode-line hook somehow interupted this resize.

**Comment by ch11ng** [comment] 2016-02-16 10:11
Does it still crash after you comment that line?

BTW `exwm-floating-hide-mode-line` has been replaced by `exwm-layout-hide-mode-line` and will be removed in the future.

**Comment by fm4d** [comment] 2016-02-16 10:24
Yes, it is still crashing. BTW: when ireplace `exwm-floating-hide-mode-line` with `exwm-layout-hide-mode-line` the bug with enlarged floating windows is back, are you able to reproduce that or it is just me?

**Comment by ch11ng** [comment] 2016-02-16 10:56
I can reproduce the first two problems but not the last one.  I've tried 64-bit Emacs 25 and 24.  Could you provide detailed steps on how to crash it?

**Comment by fm4d** [comment] 2016-02-16 11:07
Open cherrytree, right-click on the left side and choose Add Node (it should be first in the menu), dont change anything and press OK. This works for me in 9/10 cases.

**Comment by ch11ng** [comment] 2016-02-18 12:02
Fixed in 3f7722079cebd0d998239ce40457899135250a15.

**Closed by ch11ng** 2016-02-18 12:02 UTC
