### ISSUE TITLE
Various stability issues when using exwm-randr

### ISSUE THREAD

**Issue by ghost** [ch11ng/exwm#151] opened 2016-04-05 00:07 UTC
Apologies that this is less well-defined than some of my previous bug reports, but I have a harder time figuring out reproduction cases for these as they are intermittent. I can say that these occur only sometimes but become more likely the longer an EXWM session has been running with multiple monitors enabled via xrandr. I can also say that my monitors are laid out as follows:

- ``exwm-workspace-output-plist`` is
```elisp
(0 "LVDS1" 1 "DP1")
```
- When I am using the laptop at my desk, I activate the DisplayPort monitor with ``xrandr --output LVDS1 --auto --output DP1 --mode "1920x1080_60.00" --left-of LVDS1`` (where the mode used for the DisplayPort output has been defined previously).

Over time, occasionally various symptoms occur.

1) On resuming from a VT switch or returning from a screen lock (I use ``physlock``) or switching back on after screen blanking, sometimes workspaces will be placed on the wrong monitor. For example, sometimes workspace 1 will be displayed on the laptop's internal monitor (LVDS1) while the DisplayPort monitor will just be showing the default X background. However, workspace 1 will sometimes not actually be selected unless I click on it or select the workspace with the keyboard. The workspace layout will not correct itself until I run ``xrandr`` one or more times.

2) If I have a single X client on workspace 1 and normal Emacs windows on workspace 0 (or the opposite), sometimes there is a delay of several seconds after switching from workspace 1 to 0 before the keyboard responds appropriately in the selected workspace.

3) Sometimes when switching from one workspace to another, an X client such as Firefox will not actually respond to input until I click on it as well.

I am uncertain if 2 or 3 are really exclusive to randr usage or if I am only seeing them then because I only use workspaces for the multi-monitor feature (on one monitor, I find ``winner-mode`` more than good enough for dealing with window configuration).

4) Sometimes on resuming from screen blanking or locking, my touchpad will not respond, however I can see that is still working in gpm on the Linux consoles and will function again if I manually kill the X server. Combined with 1) and 3), this can leave me in a condition where I am forced to kill Emacs because I cannot regain window manager control.

Again, sorry these are less specific than my usual bug reports, but hopefully they will be of some help.

**Comment by ch11ng** [comment] 2016-04-05 05:33
Thanks for the detailed report! It's really impressive.  I'll go thru those 4 issues but first of all, you need to put that `xrandr` command into `exwm-randr-screen-change-hook`; it may resolve some problems you reported.

> 1) On resuming from a VT switch or returning from a screen lock (I use `physlock`) or switching back on after screen blanking, sometimes workspaces will be placed on the wrong monitor. For example, sometimes workspace 1 will be displayed on the laptop's internal monitor (LVDS1) while the DisplayPort monitor will just be showing the default X background. However, workspace 1 will sometimes not actually be selected unless I click on it or select the workspace with the keyboard. The workspace layout will not correct itself until I run `xrandr` one or more times.

This is because EXWM gets wrong RandR configuration info.  I don't know why this should happen but as I mentioned, reconfiguring RandR in `exwm-randr-screen-change-hook` may resolve this problem.

> 2) If I have a single X client on workspace 1 and normal Emacs windows on workspace 0 (or the opposite), sometimes there is a delay of several seconds after switching from workspace 1 to 0 before the keyboard responds appropriately in the selected workspace.

No idea about this one but if it's easily reproducible then try

```elisp
(setq xcb:keysyms:auto-update nil)
```

and see if it's gone.

> 3) Sometimes when switching from one workspace to another, an X client such as Firefox will not actually respond to input until I click on it as well.

I actually encountered this one before and I believe it's not specific to RandR settings.
I'll try to find some time to investigate this issue.

> 4) Sometimes on resuming from screen blanking or locking, my touchpad will not respond, however I can see that is still working in gpm on the Linux consoles and will function again if I manually kill the X server. Combined with 1) and 3), this can leave me in a condition where I am forced to kill Emacs because I cannot regain window manager control.

So when you said the touchpad was not working did you mean the cursor was visible but not movable?  Did keyboard shortcuts still work?  If not then you can send Emacs a USR2 signal and see where Emacs gets stuck.  Also you may try to kill certain X windows and see if EXWM start to respond again.

**Comment by wgreenhouse** [comment] 2016-04-11 17:12
Chris Feng <notifications@github.com> writes:

> So when you said the touchpad was not working did you mean the
> cursor was visible but not movable? Did keyboard shortcuts still
> work? If not then you can send Emacs a USR2 signal and see where
> Emacs gets stuck. Also you may try to kill certain X windows and see
> if EXWM start to respond again.

Yes, the cursor becomes unmovable.

However, I have discovered that this is actually a kernel module and X
input module issue (duly logged in syslog and Xorg.0.log).
Apparently the touchpad's module fails in a specific way that also
causes a page allocation failure in X.

I can resolve it by rmmoding and modprobeing the module
responsible for the touchpad (bcm5974). I think we can rule exwm
innocent of this bug. :)

I am now running your commit ddbbeda285b3b671ace99f1688e6bd3c3f84c742
and will report further progress/observations on RandR stuff.

Thanks!

**Comment by ch11ng** [comment] 2016-04-12 11:11
Thanks for your discovery! I actually experienced an invisible cursor issue after switching back from console occasionally, though the cursor would appear again after another try.  I wonder if it's also a input module issue.  Thanks again for your efforts in making these bug reports!

**Comment by ch11ng** [comment] 2016-09-23 11:26
The codes concerning the problems reported here have been changed drastically during the last few months.  So I'm closing this issue now.  Please reopen it if you can still reproduce some of them.

For problem 1, there was a bug in XELB on classifying events and that was fixed.  So I assume this problem was fixed as a result.

For problem 2 & 3, I guess they are because of the way XELB updating keyboard mapping.  I've added XKB support to XELB so the problems should get fixed.

**Closed by ch11ng** 2016-09-23 11:26 UTC
