### ISSUE TITLE
Non-Emacs windows blink when Mingus window is open

### ISSUE THREAD

**Issue by kahrkunne** [ch11ng/exwm#259] opened 2017-05-19 17:25 UTC
Opening a window with Mingus (https://github.com/pft/mingus) somewhere makes X windows (i.e. Chrome etc) blink with my Emacs background colour when in focus. 

EDIT: only happens in the mingus playlist, not in the browser or controls page

**Comment by ch11ng** [comment] 2017-05-21 18:06
The problem is mingus sets up an idle timer that would call `force-mode-line-update` to update the mode-line when Emacs gets idle, and that it also sets up the mode-line so that Emacs would call `mingus-make-mode-line-string` when updating the mode-line.  `mingus-make-mode-line-string` interacts with mpd through libmpdee that involves some process handling stuffs conflicting with XELB or EXWM.

**Comment by kahrkunne** [comment] 2017-05-21 19:22
I see. That must be related to mingus' ability to display the currently playing song.

For what it's worth, I've tried running `(defun mingus-make-mode-line-string (lambda () nil))` because I don't actually need that behaviour, but that doesn't fix the problem; the windows no longer blink the background colour, but they still blink in and out of focus.

**Comment by ch11ng** [comment] 2017-05-29 17:23
Sorry for leaving out one thing.  `mingus-make-mode-line-help-echo` also gets called during that time.  Please try redefining `mingus-mode-line-object` to something like `""`.

**Comment by kahrkunne** [comment] 2017-06-01 14:15
Doesn't solve the problem, sadly.

**Comment by ch11ng** [comment] 2017-06-03 09:14
`(setq mingus-mode-line-object "")` seems to fix the problem here.  You need to set this variable before calling `mingus`.

**Comment by kahrkunne** [comment] 2017-06-05 14:14
It does not fix the problem here. The chrome window doesn't blink the background colour anymore, but it still blinks, and typing is essentially impossible.

**Comment by ch11ng** [comment] 2017-06-11 18:03
Is #264 related?

**Comment by tidux** [comment] 2017-06-21 15:43
I'm pretty sure this is just Mingus calling `(redisplay)` and not technically a bug in exwm or Emacs.

**Comment by ch11ng** [comment] 2017-06-25 16:39
@tidux Could you elaborate on this?

**Comment by tidux** [comment] 2017-06-25 16:44
Mingus uses `(redisplay)` to redraw itself once a second.  For normal emacs windows this isn't an issue, but for X windows it causes blinking at that same pace since they get forcibly redrawn from scratch.  My fix was using other mpd clients, like ncmpcpp in urxvt, or Cantata.

**Comment by ch11ng** [comment] 2017-06-25 16:54
@tidux Thanks but did you mean Mingus indirectly called `redisplay`? I didn't find any direct call in its source (https://github.com/pft/mingus)?

**Comment by kahrkunne** [comment] 2017-06-30 05:31
`(run-with-idle-timer 1 t #'redisplay)`, which runs (redisplay) once a second, was not able to reproduce the issue, so that can't be it.

**Comment by kahrkunne** [comment] 2017-06-30 05:45
Running `mingus-cancel-timer` with mingus open seems to at least temporarily fix the problem. I'll look through the source code and see how I can reproduce the issue.

**Comment by kahrkunne** [comment] 2017-07-01 06:00
I think I'm gonna call this a Mingus bug... Thinking about it, Mingus is basically relying on being able to switch buffer sufficiently quick that it never renders.

EXWM isn't the only package which has problems with this; ace-window also has a bug when using in combination with mingus.

**Comment by ch11ng** [comment] 2017-07-09 15:53
@kahrkunne Thanks for your work!

**Comment by ch11ng** [comment] 2018-10-21 15:01
@kahrkunne I'd assume there is nothing can be done here.  So I'm closing this issue now.

**Closed by ch11ng** 2018-10-21 15:01 UTC
