### ISSUE TITLE
Various exwm-cm woes

### ISSUE THREAD

**Issue by tjackson** [ch11ng/exwm#301] opened 2017-09-01 19:27 UTC
Hi there. I would be happy to split this up into multiple issues.

If exwm-cm is running, exwm-systemtray adds a larger, non-interactive icon to the top left of my screen. Changing workspaces makes it disappear.

Wine's virtual desktop is completely invisible (but still managed by the WM), regardless of opacity setting. Wine without virtual desktop more or less works fine.

Actually the default settings look quite bizarre (opacity 80). Everything is transparent! I feel like that wasn't intended.
What I wanted to accomplish is pretty much turn off all transparency except for my terminal, which has its own opacity slider, so setting exwm-cm-opacity to 99 accomplishes that, but there is a significant performance penalty. Dragging floating windows is also extremely slow.

I have tested multiple Mesa and driver versions, but unfortunately I only have this Intel-based laptop to play on.

Seems to have been an issue for me since exwm-cm's inception, not a regression.

Thanks,
Tod

**Comment by ch11ng** [comment] 2017-09-03 13:11
> If exwm-cm is running, exwm-systemtray adds a larger, non-interactive icon to the top left of my screen. Changing workspaces makes it disappear.

I tried with both systemtray and cm modules enabled but did not notice this.  Is your EXWM up-to-date?

> Wine's virtual desktop is completely invisible (but still managed by the WM), regardless of opacity setting. Wine without virtual desktop more or less works fine.

This is completely new to me.  Could you tell me how to set this up with a few commands?

> Actually the default settings look quite bizarre (opacity 80). Everything is transparent! I feel like that wasn't intended.

This is a random value picked to clearly demonstrate that X windows can be translucent.  Users are free to pick other values.

> What I wanted to accomplish is pretty much turn off all transparency except for my terminal, which has its own opacity slider, so setting exwm-cm-opacity to 99 accomplishes that, but there is a significant performance penalty. Dragging floating windows is also extremely slow.
> 
> I have tested multiple Mesa and driver versions, but unfortunately I only have this Intel-based laptop to play on.

Sorry but I have to admit the cm module is sort of an experiment to demonstrate XELB is capable of doing compositing and rendering.  The result is not quite promising since it does not perform well on regular hardware.  One reason might be that Emacs is single-threaded so much latency is added to the compositing task.

**Comment by tjackson** [comment] 2017-09-04 00:43
Okay, it seems only Steam has the misbehaving icon. Volumeicon-alsa behaves fine. Yeah, I'm up to date. I also switched to Emacs 25 where these issues persist.

Vanilla Wine does not seem to have an invisible desktop, but Wine Staging does (version 2.15 in my case). Just run winecfg on a fresh prefix and enable virtual desktop at any resolution. Next time winecfg is run it is invisible in my case. If you think it's a Wine bug I can go bug them about it. ;)

It seems like my best bet is just not to use cm.

**Comment by ch11ng** [comment] 2017-09-10 10:33
I can't seem to get wine's virtual desktop feature to work.  Whenever I launched winecfg, I was simply presented with an extra useless blue window.  I also tried with another window manager and it turned out to be the same.

**Comment by ch11ng** [comment] 2018-01-21 13:47
I tried Telegram and it seemed to be okay with at least its first few welcome screens.  Am I suppose to login to reproduce this problem (I should admit I hate leaving many personal info)?  And did the 'black box' problem also refer to Telegram?  There seemed to be no such symptom when using counsel alone.

**Comment by ch11ng** [comment] 2018-02-18 16:45
EXWM now supports third-party compositors so I'm closing this issue.

**Closed by ch11ng** 2018-02-18 16:45 UTC
