### ISSUE TITLE
Some Wine applications don't capture keyboard input

### ISSUE THREAD

**Issue by yegortimoshenko** [ch11ng/exwm#287] opened 2017-07-31 01:04 UTC
Some Wine applications are not captured by EXWM. Input goes into an active Emacs buffer instead of going into a newly opened Wine application. Some applications (e.g. Warcraft III) crash on input with:

```
err:ole:CoCreateInstanceEx apartment not initialised
fixme:win:EnumDisplayDevicesW ((null),0,0x33f314,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f6f4,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f2f4,0x00000000), stub!
fixme:event:wait_for_withdrawn_state window 0x1006e/2600001 wait timed out
fixme:event:wait_for_withdrawn_state window 0x10068/2400001 wait timed out
```

For me it affects 3/4 of my game library. Another interesting fact: these windows ignore `exwm-manage-force-tiling` and open as floating windows despite that option set to `t`.

I've used master versions of both exwm and xelb along with `exwm-default-config`.

### Steps to reproduce:

Download Steam client: https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe

Run `wine SteamSetup.exe` and go through short installation procedure. When it's ready, it should open a window with two options: "Login" and "Create a new account". Choose either one and try to input text into any text field.

I've tried to find small free/open source games to improve this report, but strangely enough they typically don't have this exact issue (TuxRacer and quite a few others do have other issues though, more about that in another GitHub issue). The only one that reproduced this bug is FreeCiv, GTK2 version (I haven't tried SDL version): http://www.freeciv.org/download.html

**Comment by ch11ng** [comment] 2017-08-13 06:17
> Another interesting fact: these windows ignore `exwm-manage-force-tiling` and open as floating windows despite that option set to `t`.

I think they are not managed at all.  It's likely the same issue with #286.

**Comment by Ambrevar** [comment] 2018-01-17 23:12
I can confirm the issue.

Note that the flawed games would work perfectly with AwesomeWM.

Any workaround?

**Comment by ch11ng** [comment] 2018-01-21 14:09
How about switching all X windows to char-mode by default?

```elisp
(add-hook 'exwm-manage-finish-hook
          (lambda ()
            (exwm-input-release-keyboard exwm--id)))
```

**Comment by Ambrevar** [comment] 2018-01-21 16:52
That does not seem to work for me.

**Comment by lyr3** [comment] 2018-05-01 19:24
Worked in some Steam Wine games! haha

**Comment by taohansen** [comment] 2018-10-19 20:35
Running Crusader Kings 2 under Wine, I can’t get the suggested fix to work

**Comment by ch11ng** [comment] 2018-10-21 14:52
I'd assume @j3ky's solution works.  So I'm closing it now.  Please reopen it if this problem is still there.

**Closed by ch11ng** 2018-10-21 14:52 UTC

**Comment by Ambrevar** [comment] 2019-03-26 15:51
@j3ky 's solution works, but some application have issue running in a virtual desktops, e.g. mouse movements getting stuck at the desktop border (this is common in video games).

**Comment by Ambrevar** [comment] 2019-03-26 16:06
In issue #286, @ch11ng mentioned the "managed" option.
I tried the following:
```
(setq exwm-manage-configurations '((t managed t)))
```
and now reluctant Wine applications work without virtual desktop, keyboard and mouse included!

I am not sure what this `(t managed t)` means though.  I could not find much documentation around it.  Can you explain or give some pointers?  Thanks!

**Comment by ch11ng** [comment] 2019-03-31 10:42
> I am not sure what this `(t managed t)` means though.

The first `t` is the matching criteria (which means 'matching all X windows' in this case) and the second one is the value of the `managed` configuration (which means 'managing all X windows').  By default EXWM automatically decides whether an X window should be managed by checking various properties of it.  This configuration can be used to override this behavior, and should only be used when really necessary.

I'm curious about what caused EXWM to not manage the X window.  Could you provide the values of the following buffer-local variables? (You'll have to use the `managed` configuration of course, or EXWM won't manage the X window and there'll be no buffer.)

```elisp
exwm-window-type
exwm--mwm-hints-decorations
exwm--hints-input
exwm-transient-for
exwm--fixed-size
```

**Comment by Ambrevar** [comment] 2019-04-01 14:51
Thanks for the explanation.

> The first `t` is the matching criteria (which means 'matching all X windows' in this case)

I dug into the code to figure that this `t is `eval`ed against the
current buffer, so it can be a function of zero parameter returning a
boolean.  I think we should add this to the docstring.


Here are the values you asked for:

- exwm-window-type (346)
- exwm--mwm-hints-decorations nil
- exwm--hints-input nil
- exwm-transient-for nil
- exwm--fixed-size t

**Comment by ch11ng** [comment] 2019-04-05 09:02
> I dug into the code to figure that this `t is `eval`ed against the
current buffer, so it can be a function of zero parameter returning a
boolean.

Exactly.  I'll clarify that.

> - exwm-window-type (346)

It seems to be this one, but I forgot to mention that the numerical value is not quite useful.  Could you translate it with `(x-get-atom-name 346)` (the numerical value can change across sessions so you probably need to fetch an updated one)?

**Comment by Ambrevar** [comment] 2019-04-05 11:41
(x-get-atom-name (car exwm-window-type))

_NET_WM_WINDOW_TYPE_NORMAL

**Comment by ch11ng** [comment] 2019-04-07 12:02
@Ambrevar It's actually `_MOTIF_WM_HINTS` that prevents X windows from being managed.  That code is kind of a workaround and was added for Java applications which IIRC don't set override-redirect on their menus, or lots of floating frames would be created.  For now I recommend your solution, though X window matching should be done more precisely.

**Comment by Ambrevar** [comment] 2019-04-08 17:48
Can you explain where `_MOTIF_WM_HINTS` comes from?

Should I open a new issue about this?

**Comment by ch11ng** [comment] 2019-04-14 06:08
`_MOTIF_WM_HINTS` is set by applications (or the toolkit they are built on).  There is nothing wrong on the application side but the way we handle this property.
