### ISSUE TITLE
Firefox context menu is on wrong screen

### ISSUE THREAD

**Issue by DamienCassou** [ch11ng/exwm#351] opened 2018-01-16 10:33 UTC
1. get two screens, one exwm workspace each
2. start Firefox (I use nightly) on the *non-primary* screen
3. right-click somewhere on a webpage

Actual: you get a context menu in the *primary* screen

Expected: a context menu on the screen where Firefox is (the *non-primary* screen)

/cc @NicolasPetton who can reproduce the problem on his computer (very similar setup)

**Comment by DamienCassou** [comment] 2018-01-16 10:43
I've updated the ticket description because it seems opening Firefox on the primary screen gives me a context menu on the same screen (which is good). To reproduce the problem, I have to open Firefox on the non-primary screen.

**Comment by ch11ng** [comment] 2018-01-21 13:55
Sorry but I have no multiple monitors setup at the moment.  I'll try this later.  And at the meantime could you verify with which was the first version of Firefox this problem can be reproduced?  There seems to be no such issue filed before for it.

**Comment by DamienCassou** [comment] 2018-01-22 08:38
The first bad release is [49.0b1](https://ftp.mozilla.org/pub/firefox/releases/49.0b1/linux-x86_64/en-US/). You might be interested in [release notes for 49](https://www.mozilla.org/en-US/firefox/49.0/releasenotes/).

```
firefox-GOOD-40.0.tar
firefox-GOOD-45.0.tar
firefox-GOOD-47.0.tar
firefox-GOOD-48.0.0.tar
firefox-GOOD-48.0.2.tar
firefox-BAD-49.0b1.tar
firefox-BAD-49.0.tar
firefox-BAD-50.0.tar
```

**Comment by vbuaraujo** [comment] 2018-01-28 16:11
I'm having this same problem. I reinstalled my system from scratch yesterday and now I observe this behavior in Firefox 58. (Previously I was using Firefox 45.) The right-click menu always shows up in my external monitor, regardless of which window Firefox is in.

How do you tell which monitor is primary?

**Comment by vbuaraujo** [comment] 2018-01-28 16:30
Well, Firefox seems to be computing the menu position relative to the screen the window is in, but then using the position relative to the top left of all screens to show it. For example: My external monitor is wider than my laptop's builtin one. If I set the external monitor to the right of the builtin one, and I put Firefox in the external monitor, and I right-click closer to the left of the window, then I see the menu on the builtin monitor. But If I right-click closer to the right end of the window (at a point too far right to show up in the builtin monitor), the menu shows up on the left side of the external monitor. So it seems Firefox is having trouble finding the beginning of the screen it is in (or determining which screen it is in).

**Comment by DamienCassou** [comment] 2018-01-29 08:28
I confirm @vbuaraujo findings. It's not about which screen is primary. It's about which screen is on the right.

**Comment by ch11ng** [comment] 2018-02-04 14:42
I managed to reproduce this by offseting the workspace and yes only Firefox is affected.  No idea how Firefox computes the position for its context menu.  I'm afraid we have to bisecting Firefox to find the cause.

**Comment by ch11ng** [comment] 2018-02-18 16:49
I think with the latest code the problem is resolved.  Please give it a try.

**Comment by vbuaraujo** [comment] 2018-02-18 17:26
Do I need a development version of Emacs to run the current version of EXWM / XELB? I'm running Emacs 25.2.2 and I get a "XELB ERROR: (wrong-type-argument arrayp nil)" on startup when I try to run it. I'm sending the backtrace attached.
[exwm-debugger-output.txt](https://github.com/ch11ng/exwm/files/1734923/exwm-debugger-output.txt)

**Comment by ch11ng** [comment] 2018-02-19 15:16
> Do I need a development version of Emacs to run the current version of EXWM / XELB?

You need to fetch the latest code for both EXWM and XELB.  I can not reproduce this with Emacs 24/25/26/27

**Comment by ch11ng** [comment] 2018-02-25 16:49
The bug is fixed with the latest release so I'm closing it.

**Closed by ch11ng** 2018-02-25 16:49 UTC
