### ISSUE TITLE
About "'Iceweasel' is not responding...."

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#132] opened 2016-03-02 14:35 UTC
Open xfce4-terminal and iceweasel, when i kill xfce4-terminal's buffer, 
"'Iceweasel' is not responding. Would you like to kill it? (yes or no) " showed, why?

**Comment by ch11ng** [comment] 2016-03-03 09:47
> Open xfce4-terminal and iceweasel, when i kill xfce4-terminal's buffer, 
"'Iceweasel' is not responding. Would you like to kill it? (yes or no) " showed, why?

Because Iceweasel was busy.  But how can I reproduce this issue?

**Comment by tumashu** [comment] 2016-03-03 10:23
1. start iceweasel
2. start nautilus
3. kill nautilus's buffer
show: "'Iceweasel' is not responding. Would you like to kill it? (yes or no) "

**Comment by ch11ng** [comment] 2016-03-03 11:37
Fixed in fe9be0b3efab284dae9eb1de37e97a70a9e08bd2.

**Closed by ch11ng** 2016-03-03 11:37 UTC
