### ISSUE TITLE
EXWM with Athena+Xaw3d confuses xcape setting Caps Lock to Ctrl+Escape

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#285] opened 2017-07-28 14:49 UTC
This is admittedly a very specific one...

While the wiki recommends a GTK3 build of Emacs, I prefer Athena+Xaw3d (lighter, less dependencies) so I gave it a try.
As far as I can tell, everything works like a charm but for one thing: in my `.xprofile` I call

    xcape -e 'Control_L=Escape'

so that Caps Lock can be used both as a `C-` modifier and as the Esc key (when pressed and released).
This is very useful when using vi-like bindings (e.g. Evil).

With EXWM the Caps Lock key won't work as intended: the modifier still works but the Esc key does not produce anything if no other key is pressed within a second.  So I have to double-tap Caps Lock to produce an Esc. (Plus an extra <C-escape>? I'm not sure which one is actually effective.)  Very annoying.

Such a tiny nit but that alone is enough to force me to switch to a GTK3 build.
Such a tiny nit, and yet it would be so nice to see it fixed.

**Comment by ch11ng** [comment] 2017-07-30 17:48
Do you have the problem when you work on a normal buffer?

**Comment by Ambrevar** [comment] 2017-07-30 18:20
By normal you mean non-EXWM buffers? Yes I do. In fact I don't remember if I have the problem in EXWM buffers.  I can try later.

**Comment by Ambrevar** [comment] 2017-08-03 19:51
I've re-emerged Emacs with the Athena-Xaw3d USE flags (I use gentoo) and the issue is gone.
Not sure what went wrong in the first place.

**Comment by Ambrevar** [comment] 2017-08-14 08:54
It would have been too simple: the issue is still there and happens at random.

- Within one session, the Caps Lock key can lag for a while as described previously.  This behaviour may disappear after a while.

- Some buffers will suffer from the issue while others won't.

**Comment by vyp** [comment] 2017-08-28 13:42
@Ambrevar I'm sorry this is off topic and unrelated to this issue, but in the interest of being potentially helpful to you, perhaps you can consider using [interception-tools](https://gitlab.com/interception/linux/tools) with [caps2esc plugin](https://gitlab.com/interception/linux/plugins/caps2esc) instead of xcape? (Just a suggestion.)

**Comment by Ambrevar** [comment] 2017-08-28 13:48
Thanks for the tip, I'll look into it.

**Comment by Ambrevar** [comment] 2017-08-31 23:00
@vyp Have you managed to run it?  With the following config
```
- JOB: "intercept -g /dev/input/by-id/usb-Logitech_Logitech_USB_Keyboard-event-kbd | caps2esc | uinput -d /dev/input/by-id/usb-Logitech_Logitech_USB_Keyboard-event-kbd"
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
```
I get the error

```
> sudo udevmon -c ~/temp/interception/config.yaml
libevdev_uinput_create_from_device failed: No such file or directory
```
I had a look at the source code: as far as I understand it, it is failing to find `/dev/input/by-id/usb-Logitech_Logitech_USB_Keyboard-event-kbd` for some reason.

**Comment by vyp** [comment] 2017-09-01 04:17
@Ambrevar Yes I'm using it right now. That's unfortunate.. :disappointed:
I don't know if this would change anything but did you try just using `$DEVNODE` for the `devnode`? (That's what I'm using.)

**Comment by Ambrevar** [comment] 2017-09-01 07:07
I did and I got the same error.

**Comment by vyp** [comment] 2017-09-01 08:18
:/ Hmm, what does that point to, did you try specifying that /dev/input directly? (I'm not sure if that would be good enough to use as a final solution though even if it does work.) Maybe you should open a ticket at the repository.

Otherwise, I'm sorry, I figured it would have potentially helped because the caps2esc plugin does mainly the same thing as `xcape -e 'Control_L=Escape'`, but at a different 'level' on the stack compared to xcape, so I thought it might not encounter the problem you're running into in this issue.

**Comment by Ambrevar** [comment] 2017-09-01 08:29
I tried on Arch Linux and it works :p 
I think you are right: the whole reason to be for interception is that it works at the kernel level, it does not require X, hey, it even works in a TTY!  So that would probably fix my issue.
I'll try to fix my issue with Gentoo.

**Comment by Ambrevar** [comment] 2017-09-01 09:15
Still failing.  I've reported the issue upstream:
https://gitlab.com/interception/linux/plugins/caps2esc/issues/2

**Comment by vyp** [comment] 2017-09-01 21:38
Yep and it should also work on Wayland too so it's more future proof as well. :tada:

**Comment by Ambrevar** [comment] 2017-09-01 21:57
Unfortunately EXWM does not :/

**Comment by vyp** [comment] 2017-09-02 00:01
True, but that's the case for almost every X window manager so it's sort of "out of scope" or unfair to criticize EXWM for that. :wink:

Also I was wondering for this xcape issue, do you not get this issue in other window managers? Because lately for me (past few months), not even `xcape -e 'Control_L=Escape'` has been working properly for me in various window managers. For example, pressing caps lock properly registers as escape in urxvt, xterm and (gtk) emacs. But I'd have to press caps lock three times to register an escape in other programs such as st and zathura.

So if you do get this issue in other window managers, maybe this is an xcape issue instead of exwm. And also, I have an older machine where xcape works properly everywhere, so I updated xcape on it expecting the caps lock -> escape mapping to fail (for example in zathura), but it still seemed to work fine everywhere. So I feel like maybe it's not even an xcape issue but some X regression or something which makes xcape not work properly under some type of window. But that's just a guess and I never looked into it further than that and switched to interception-tools. (For reference if it helps anyone reading this, that old machine's version of X is 1.17.2, and the version of X where I'm having problems with xcape is 1.19.3.)

**Comment by Ambrevar** [comment] 2017-09-02 06:53
Interesting,  I haven't tested that far.
I'm on Gentoo with X 1.19.3.

**Comment by mallt** [comment] 2017-10-25 20:25
@Ambrevar Did you have any luck finding out how to make xcape work with EXWM? Thanks!

**Comment by Ambrevar** [comment] 2017-10-25 20:34
@mallt: It's always been working on a GTK3 build.  I haven't investigated more than that about the Athena+Xaw3d.  @vyp's last comment gives some new directions to follow.

**Comment by mallt** [comment] 2017-10-25 20:44
@Ambrevar Ok thanks!

**Comment by Ambrevar** [comment] 2017-10-25 20:49
Are you experiencing the same symptoms on Athena+Xaw3d?

**Comment by mallt** [comment] 2017-10-25 20:57
Actually I'm currently using a build of Emacs from the master branch without X toolkit on which `xcape` works fine while running in KDE. But when trying out EXWM I cannot seem to get it working. I will need a GTK3 build then because I'm heavily dependent on `xcape` :).

**Comment by Ambrevar** [comment] 2017-10-25 21:05
What do you mean, "without X toolkit"? The terminal version? EXWM cannot use that: it needs X support built-in to run on X.

**Comment by mallt** [comment] 2017-10-25 21:15
No, it's the GUI version, but building with the `--with-x-toolkit=no` option results in some very simple menus and toolbars, but I don't use them so I don't really notice.

**Comment by Ambrevar** [comment] 2017-10-25 21:26
`--with-x-toolkit=no` means no X.  If it fires up a graphical version, then you had some conflicting options.
See the content of the `system-configuration-options` variable.

**Comment by mallt** [comment] 2017-10-25 21:35
No it's a graphical version, but very minimal, you can see some screenshots of it on [emacs wiki](https://www.emacswiki.org/emacs/ToolKit).

**Comment by Ambrevar** [comment] 2017-10-25 21:38
My bad, I did not know that.  Fascinating! :D

**Comment by mallt** [comment] 2017-10-26 22:31
In case it helps someone else, I managed to get xcape working in EXWM by applying 2 changes to the command compared to the command in KDE:
- remapping `Control_L` instead of `Caps_Lock`
- using a lower case for the key to map to (in my case I map the caps lock key to `ù` when pressed and released, which I had to refer to as `ugrave` instead of `Ugrave`)

So the xcape commands are:
- KDE: `xcape -e 'Caps_Lock=Ugrave'`
- EXWM: `xcape -e 'Control_L=ugrave'`

**Comment by akater** [comment] 2018-01-11 07:24
I experienced the same, or at least very relevant bug. I use xcape to make SPC act as Ctrl when long pressed. Athena+Xaw3d+EXWM made SPC only useable as Ctrl... unless Firefox is running, in any workspace. (Other windows, gtk or not, in contrast to Firefox, did not “help”).

However, running Emacs+EXWM built `--with-x-toolkit=no`, resolved this. (Note: again, this is a slightly different use of xcape than described above.) At least that's how it looks at the moment.

**Comment by ch11ng** [comment] 2018-01-14 16:14
@akater,

It's surprising that Firefox can act as a remedy for this.  It seems to be so remotely related.

And what's the version of Emacs in use?  @mallt reported `--with-x-toolkit=no` did not work.

**Comment by akater** [comment] 2018-01-15 18:35
>And what's the version of Emacs in use?  @mallt reported
>`--with-x-toolkit=no` did not work.

26.0.90

**Comment by medranocalvo** [comment] 2018-10-26 18:32
It's been a long time, and there have been quite some changes in input handled since January.  Is this still happening?

**Comment by Ambrevar** [comment] 2018-10-27 17:47
I've retested this on 0.20.  My conclusion is as per this thread:

- With Athena + Xaw3D and xcape, ESC behaves strangely.  After more testing, it seems that it's the _duration_ of the keypress that matters: if too short or too long, it's ignored.  In practice it's very hard to use.
- Using `--with-x-toolkit=no` everything works perfectly.

This bug is probably not going to get fixed and I don't see a particular reason to use Athena instead of the "no" toolkit, so for my use case it's an acceptable workaround.

My suggestion is to recommend this in the README: "prefer 'no' over 'athena'".  Then it's safe to close this issue.

**Comment by akater** [comment] 2018-10-28 03:51
athena+Xaw3d still doesn't work for me with xcape. GNU Emacs 26.1-r3 on
Gentoo, exwm 0.20. Same baffling effect with Firefox.

I second the suggestion to recommend `no' over `athena'.

**Comment by medranocalvo** [comment] 2018-10-28 08:42
Thank you both for testing again.  That the problem is corrected when Firefox is running is incomprehensible to me.

I just tried `xcape` on my setup.  I use `--with-x-backend=lucid`.

```
$ ./xcape -d -e 'Control_L=Escape'
Assigned mapping from "Control_L" ( keysym 0xffe3, key code 67)
to "Escape" (keysym 0xff1b, key code 61)
sig_handler running...
Intercepted key event 2, key code 67
Key pressed!
Intercepted key event 3, key code 67
Key released!
Generating Escape!
Ignoring generated event.
Ignoring generated event.
^[Intercepted key event 2, key code 67
Key pressed!
Intercepted key event 2, key code 42
^CCaught signal 2!
sig_handler exiting...
main exiting
```

It seems to work fine.  Have you tried `xcape`'s debug mode?  Could you post the output with/without Firefox?

The wiki is open for everyone to contribute.  I drafted an entry in section "Known Issues".  Please review it and improve it if possible.

**Comment by Ambrevar** [comment] 2018-10-28 11:29
Here is the output with Athena and without Firefox when `Esc` is not working:

```
Key pressed!
Intercepted key event 3, key code 66
```

And when `Esc` is working:
```
Key released!
Generating Escape!
Ignoring generated event.
Ignoring generated event.
...
```

**Comment by medranocalvo** [comment] 2018-10-28 11:41
That brought little further information: it seems that `xcape` receives no KeyRelease event.  I assume the `athena` toolkit is doing something naughty, or there's a bug in `xcape`.  Perhaps the `lucid` toolkit fulfills your initial wish.  I'm closing this issue following your suggestions, thank you all.

**Closed by medranocalvo** 2018-10-28 11:41 UTC
