### ISSUE TITLE
New windows are marked read-only initially

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#246] opened 2017-04-15 17:18 UTC
Hi,

With the latest master, I get the following error in the mini-buffer when I type keyboard commands immediately after opening a new X11 program (after it's window is dispalyed).

funcall-interactively: Buffer is read-only: #<buffer URxvt>

This error seems to go away if I delay typing for a second after X11 program started.

Thanks,
Chaitanya

**Comment by bvk** [comment] 2017-04-15 18:41
It seems this issue aalso happens with existing windows also. I noticed the same behavior when I switch from one workspace to another workspace with an existing X11 window and type any keys immediately after switching the workspace.

This doesn't used to happen with v0.11 branch -- which is the branch I was using before trying the latest master.

**Comment by ch11ng** [comment] 2017-04-16 13:23
I don't think I have the problem.  Is XELB up-to-date? If so could you try with a minimal configuration?

**Comment by bvk** [comment] 2017-04-17 00:52
Yes, xelb is up to date, at origin/master.

It was rather tough to reproduce this with minimal configuration because of not having keybindings to start X11 programs. I use the following keybindings format to start X11 programs:

```
;; "C-c i" is for internet browser.
(exwm-input-set-key
 (kbd "C-c i")
 (lambda () (interactive)
   (start-process "browser" "*Messages*"
		  "google-chrome")))
```

Do you think using ```start-process``` could cause any races? Could you suggest any other preferred alternative to ```start-process```?

**Comment by bvk** [comment] 2017-04-17 02:17
Since this issue is happening even when I am not starting new X11 programs but only switching between workspaces, could you confirm if this keybinding assignment format is correct and doesn't cause any race?

```
(exwm-input-set-key
 (kbd "C-c o") #'exwm-workspace-switch)
```

Basically, I use ```C-c o 5``` to switch to workspace ```5```.

**Comment by bvk** [comment] 2017-04-17 20:11
This issue seems to happen only when I am switching from a workspace with normal buffers to a workspace with X11 programs.  Otherwise, i.e., when switching between workspaces with normal buffers or between workspaces with X11 programs doesn't cause this issue.

For example, workspace 1 has normal emacs buffers and workspace 2 has google-chrome window. *Both these workspaces are on the external monitor using exwm-randr -- I will try without external monitor later.* I have the following keybinding so that I can switch to workspace 1 using ```C-c o 1``` from anywhere and switch to workspace 2 using ```C-c o 2``` from anywhere.

```
(exwm-input-set-key
 (kbd "C-c o") #'exwm-workspace-switch)
```

Assuming I am on workspace 1, following keys ```C-c o 2 C-c o 1``` should make exwm switch to workspace 2 and then back to workspace 1. But the behavior I see is, exwm switches to workspace 2 and sends the second ```C-c``` instance to the mini-buffer and keys ```o 1``` to the google-chrome window.  Mini-buffer just waits at ```C-c``` while all following keys go the google-chrome window. At this point, if I type ```C-c o 1``` again the ```C-c``` part triggers ```C-c is undefined``` message in the mini-buffer and the ```o``` key causes ```Buffer is read-only: #<buffer *EXWM*>``` message printed in the mini-buffer.

**Comment by bvk** [comment] 2017-04-19 18:24
I could reproduce above behavior with the below minimal configuration (with only laptop display no external monitor):

```
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
(exwm-input-set-key
 (kbd "C-c o") #'exwm-workspace-switch)
```

This issue doesn't happen on v0.11 branch -- which is what I was using before. I will try with v0.12 branch later.

**Comment by tumashu** [comment] 2017-04-22 13:34
I have faced this bug too ....

```
funcall-interactively: Buffer is read-only: #<buffer Exwm:Firefox>
```

**Comment by ch11ng** [comment] 2017-04-23 15:41
Fixed in 2b7449ea425df236471496cd96f061d70f3ba15a.

**Closed by ch11ng** 2017-04-23 15:41 UTC

**Comment by prosoitos** [comment] 2019-02-02 03:31
I have been experiencing this lately. For instance:

`funcall-interactively: Buffer is read-only: #<buffer qutebrowser>`

**Comment by ch11ng** [comment] 2019-02-04 14:47
@prosoitos Do you have exwm-randr module enabled? If so, could you confirm if you can reproduce this issue with it disabled?

**Comment by ch11ng** [comment] 2019-02-05 05:36
@prosoitos Does 44629818bacf3e3a10a37e570fdee2e963dbcc7b fix your issue?

**Comment by prosoitos** [comment] 2019-02-05 09:12
Thanks! Will look at this and get back to you tomorrow.

**Comment by prosoitos** [comment] 2019-02-05 22:53
> @prosoitos Does [4462981](https://github.com/ch11ng/exwm/commit/44629818bacf3e3a10a37e570fdee2e963dbcc7b) fix your issue?

It does :slightly_smiling_face: 

Thank you for your very quick help @ch11ng ! Much appreciated!

**Comment by prosoitos** [comment] 2019-02-06 02:19
I just came across a situation in which I still get `funcall-interactively: Buffer is read-only: #<buffer qutebrowser>`.

As you know from #539, I always end up with many workspaces that I have to kill. If qutebrowser is in a workspace which I kill, it gets moved to the previous workspace and is read-only until I switch to another workspace and comes back to it.

**Comment by ch11ng** [comment] 2019-02-06 11:46
@prosoitos If it doesn't bother you then I'll just leave this bug there for this edge case since I've planed refactoring of the workspace module.

**Comment by prosoitos** [comment] 2019-02-07 02:13
No worries. As you say, it is an edge case.

**Comment by prosoitos** [comment] 2019-02-15 10:55
@ch11ng Now that I fixed my issue with emacsclient (see #539), that edge case is no problem whatsoever anymore as I won't have to kill workspaces anymore.

I thought that I would mention however that buffers do become read-only on occasion. It may be when too much is running at once (I am not out of memory though). Giving the machine some time can bring things back to normal, but often a reboot is needed and then everything is fine again.

This problem has nothing to do with new windows, so probably not the best issue to comment on. If this starts happening too frequently, I will open a new issue.

**Comment by moritzschaefer** [comment] 2019-03-15 11:36
> This problem has nothing to do with new windows, so probably not the best issue to comment on. If this starts happening too frequently, I will open a new issue.

@prosoitos Have you opened a new issue? I'm experiening similar bugs: Sometimes when I switch to another workspace with an X window, inputs (key or mouse) won't get forwarded to the X window and emacs shows: "Buffer is readonly: #<buffer qutebrowser ...>" for example. Switching randomly between workspaces occasionally fixes this (it's about a 50/50 chance that switching to the workspace with qutebrowser results in working inputs or the mentioned error). 
What fixes this as well is clicking on "char" in my powerline and then clicking it again (char->line->char). Using my hotkeys for changing to line-mode and then to char-mode again changes the mode (as indicated in the status bar), however it does not resolve the issue (i.e. the X window still doesn't receive any inputs).

**Comment by prosoitos** [comment] 2019-03-17 07:24
I have not opened an issue about it.

It seems to be happening when I have too much going on at the same time. Switching between windows or workspaces always fixes it for me. But often that is a sign that things are starting to go wrong and I restart Emacs.

Feel free to open an issue on this since I have not. I still do have the problem, but it seemed to me hard to pinpoint.
