### ISSUE TITLE
Symbol's value as variable is void: msw

### ISSUE THREAD

**Issue by dxknight** [ch11ng/exwm#5] opened 2015-08-05 18:12 UTC
When a program is launched (e.g. firefox), nothing appears and I get the messages:

error in process filter: -: Symbol's value as variable is void: msw
error in process filter: Symbol's value as variable is void: msw

According to proced, firefox is running but I can't see it.

I'm running GNU Emacs 24.4.1 (i686-pc-linux-gnu, X toolkit, Xaw3d scroll bars).

By the way, awesome project!

**Comment by ch11ng** [comment] 2015-08-05 23:03
I believe this is due to a problem of XELB on 32-bit platform. I've corrected it and you may pull that update and have a try.

**Comment by dxknight** [comment] 2015-08-06 06:50
**xcb:-pack-u4-lsb** errors out trying to make 1000000000 into a 4 byte vector.

I added a 'float' when calculating lsw in the let*:

       (lsw (truncate (- value (* (float msw) #x10000))))

This appears to have fixed it.

I did try (lsh msw 16) as in xcb:-pack-u4, but it couldn't handle the arithmetic when value was 1000000000.  I haven't changed xcb:-pack-u4 but it seems to be ok as it is so far.

**Comment by ch11ng** [comment] 2015-08-06 07:13
Yes. The conversion on 32-bit platform is both inefficient and problematic since the maximum integer there is #x1FFFFFFF (30 bits). I will find a 32-bit installation and check if there are other errors.

**Comment by ch11ng** [comment] 2015-08-06 13:25
I believe the problem is fixed by ch11ng/xelb@1916894.

**Closed by ch11ng** 2015-08-06 13:25 UTC

**Comment by dxknight** [comment] 2015-08-06 13:41
Brilliant!  many thanks.

**Comment by tumashu** [comment] 2015-08-06 13:52
good job.....
