### ISSUE TITLE
ace-window can't jump to exwm buffer on another workspace

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#194] opened 2016-09-06 01:48 UTC
Ace-window is a quick way to jump to window by typing window label. I have two workspaces on two monitors. Ace-window can jump to non exwm buffers on different workspaces. It also works with exwm buffers on the same workspace, but the buffer label is only visible in the modeline with this setting.
 
     (ace-window-display-mode t)

It would be very nice if ace-window works for all exwm buffers.

**Comment by ch11ng** [comment] 2016-09-07 11:24
Hi, I'm going to be away for two weeks and I'll look into this issue after I'm back.  Sorry for the delay!

**Comment by jtamagnan** [comment] 2016-09-08 16:35
I can confirm this issue, I haven't updated in a few months so I do not know when it was introduced

**Comment by ch11ng** [comment] 2016-09-21 10:31
Sorry for the long delay.  I'm afraid I need to check the source of `ace-window` to determine the problem.

@jtamagnan, which behavior were you referring to? Switching to an `exwm-mode` buffer on another workspace, showing the label of an `exwm-mode` buffer or something else?

**Comment by jtamagnan** [comment] 2016-09-21 17:37
Switching windows that are in a different frame/workspace.

The following code works when the windows are in the same frame but not on different frames.

``` lisp
(select-window (get-buffer-window "EXWM: Firefox" t))
```

**Comment by ch11ng** [comment] 2016-09-23 11:04
Usually I'd avoid touching the code relating to input focus.  But to fix this issue I committed 84dad20d6648638443bc7c731d7d60bbf0872bdb.  Please give it as much test as you can.  I'll leave this issue open until the next release.  That commit can be reverted if it proves breaking anything.

As for the other problem with ace-window, or invisible labels for `exwm-mode` buffers, I don't think it can be fixed.  ace-window uses overlays for displaying them so they are always invisible unless the corresponding X window get hidden (which is unlikely possible since no event or hook is available for overlays).

**Comment by jtamagnan** [comment] 2016-09-23 14:34
Alright, I'll get started on using it now. One question though. Do you know why it used to work flawlessly and what changed it?

**Comment by ch11ng** [comment] 2016-09-23 15:33
> Do you know why it used to work flawlessly and what changed it?

It was broken roughly at 76ced38ae43a9192ed97ca35dd1cc83c62b2a073.  By then the dynamic workspace feature was just introduced and the old input focus mechanism didn't work quite stably thus I reworked one.

**Comment by jtamagnan** [comment] 2016-09-23 17:06
Awesome thanks for everything. This fix seems to be working and I'll be using it every day at work and will let you know if I encounter any problems. It also works great with macros!

**Comment by ch11ng** [comment] 2016-10-01 11:15
Since there seems to be no problem I'm closing it now.

**Closed by ch11ng** 2016-10-01 11:15 UTC
