### ISSUE TITLE
Cannot change mini-buffer position option

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#429] opened 2018-05-22 06:41 UTC
If I change the default option to `top (auto-hide)` or `bottom (auto-hide)` via `customize-group`, this has no effect. If I change the option in my init file and reboot, `exwm` crashes. With the default option (`bottom (fixed)`), things are working properly.

I am on Arch Linux with LXDE.

Thank you!

**Comment by ch11ng** [comment] 2018-05-27 15:33
> If I change the default option to top (auto-hide) or bottom (auto-hide) via customize-group , this has no effect.

You'll need to start a new session for that to take effect.  If you've already done that, please check if the value of `exwm-workspace-minibuffer-position` is set to `'top` or `'bottom` depending on what you choose.

> If I change the option in my init file and reboot, exwm crashes.

Emacs should never crash.  However, I'm not able to reproduce it, even with LXDE.  Please try starting EXWM with `emacs -Q -L /path/to/xelb/ -L /path/to/exwm/ --eval "(setq exwm-workspace-minibuffer-position 'top)" --eval "(require 'exwm)" --eval "(exwm-init)"` and see if Emacs still crashes.

**Comment by prosoitos** [comment] 2018-05-27 20:15
> You'll need to start a new session for that to take effect.

OK. I am used to changes done in `customize-group` to take effect directly, so I was surprised.

If I do this, then reboot, I have the same behaviour as if I change the settings directly in my init file, then reboot (as one would expect): things are messed up, bindings are not responding, the frames are a little off and within minutes of trying to do anything, everything goes to hell. Sometimes I manage to close properly and sometimes it freezes before I can do that and I have to force stop. So emacs doesn't exactly "crash", but goes to hell.

I will try your suggestions when I have a bit of time (thank you for your help!!!!) and report here. For now, I have accepted that my mode-line and minibuffer have to be fixed at the bottom and that's ok.

**Comment by ch11ng** [comment] 2018-06-03 08:44
Your Emacs must have been heavily customized it seems.  Try a minimal configuration may help finding out which packages are in conflict with EXWM.

**Comment by prosoitos** [comment] 2018-06-03 19:05
Yes... I have a very large init file and am running lots of packages... for now, I have settled on leaving the mini-buffer always visible and at the bottom. I will explore when I have more time as it seems that it could be a big debugging operation if you have no guess as to what could be the problem.

**Comment by medranocalvo** [comment] 2018-10-08 16:35
@prosoitos, have you had the chance to debug this?  Does still happen with the newest code?

**Comment by prosoitos** [comment] 2018-10-08 21:37
Sorry: since this is not a critical option, I decided to keep the mini-buffer at the bottom and not worry about it anymore. Now that I have been using exwm for months (thank you again so much for it! :slightly_smiling_face: ) and developed a workflow with it, I am happy to keep my settings as they are. So feel free to close this issue, whether the option would or would not work for me now. If it doesn't work for someone else who wants to use it, I guess they can always reopen it.

(Note that if you really want me to test it with my settings to double-check the robustness of your code, etc., I certainly could.)

Thank you!!!

**Comment by medranocalvo** [comment] 2018-10-10 15:32
Well, I redirect your thanks to @ch11ng, the creator of EXWM.

With regards to your offer for help... I take it.  Just today we had a new issue related to the minibuffer position: #489.  There's also a recent bug fix related to the minibuffer position in #484, pending merging.  Could you check whether #484 works in your setup?

**Comment by prosoitos** [comment] 2018-10-13 04:53
Things are a lot better, but still some glitches with the `bottom (auto-hide)` option.

As soon as anything appears in the minibuffer, the mode-line disappears. Some functions seem to break. I tried it just for a few minutes since I am not interested in messing up with this option anymore, so this is probably not exhaustive and it might have to do with some of my settings in my init file. So this is not a really useful report. But it would take a lot of time to dig deeper into this.

What I did notice in my brief try is that, `org-agenda-show-and-scroll-up` doesn't run in the *Org Agenda*.

 `top (auto-hide)` seemed ok, but I haven't tried it long enough to be sure that it doesn't create issues while doing one thing or another (and I didn't try `org-agenda-show-and-scroll-up`).

**Comment by ch11ng** [comment] 2018-10-14 08:33
I always have this option set to `bottom` and it seems working fine at least for my workflow.  Since this feature relies on a dedicated minibuffer frame (a totally valid but rare setting), there can be some extensions incompatible with this feature though.

> As soon as anything appears in the minibuffer, the mode-line disappears.

@prosoitos Did you mean the mode-line is obscured by the minibuffer? Does it appear again when the minibuffer becomes inactive? If so then this is by design (everything remains intact after activating/deactivating the minibuffer which is different from the default behavior).

**Comment by prosoitos** [comment] 2018-10-15 01:05
> Did you mean the mode-line is obscured by the minibuffer? Does it appear again when the minibuffer becomes inactive? 

Yes

> If so then this is by design (everything remains intact after activating/deactivating the minibuffer which is different from the default behavior).

OK. All good then. I found it distracting, but it probably is because I am not used to it.

**Comment by medranocalvo** [comment] 2018-10-15 15:38
@prosoitos, thank you for carrying out the test.

I'm closing this issue as the original problem is resolved.

With regards to your comments, a possible improvement to the minibuffer-position would be to be able to configure a minimum height, for example one line.  In that case it would replicate a normal minibuffer for the usual case, but wouldn't push every other window when it grows.  I'll let someone interested fill this feature request.

**Closed by medranocalvo** 2018-10-15 15:38 UTC
Labels: moreinfo

**Comment by prosoitos** [comment] 2018-10-15 16:13
@medranocalvo. No problem. Sorry I didn't push the debugging effort further with the agenda buffer. I have lost interest to play with this option since it seems to break things for me and I am happy to have it fixed at the bottom anyway. All I can say is that, while in the *Org Agenda* buffer, it normally is easy to pop up the agenda file corresponding to an agenda event, but with the auto-hide option, the file would not open and I would get an error message instead (while all works normally with the default option).
