### ISSUE TITLE
ido-switch-buffer dont works

### ISSUE THREAD

**Issue by spiderbit** [ch11ng/exwm#186] opened 2016-08-08 21:31 UTC
I have pushed the menu key for my shortcuts, so I use Menu + u for ido-switch-buffer, all my other menu + \* key bindings work, but this one not.

I get the message:

`End of buffer`

Well I just looked what I see on Messages:
`xah-search-current-word: End of buffer`

So that message makes sense if it calls that functions instead.

But this function is bound to "menu + f" not "menu u".

So that explaines why menu + 3 works cause thats not different in another keyboard layout.

So even I use dvorak inside emacs and outside of X windows my shortcuts are also dvorak, and in the X window when I type here as example that text, I use also dvorak.

After pressing menu, I think exwm switches my keyboard layout to qwerty. and afterwards back to dvorak.

Very strange bug, it works the other way around, when I press now <menu> + g, switch buffer pops up, g is the position of u in qwerty.

I am not 100% shure its exwms fault, could also be xah-fly-keys fault, but I doubt it, cause it works perfectly till I use external X Apps.

Maybe its related cause in TTY I did not figure out in fedora how to permanently switch to dvorak, so somehow exwm falls back to the "system" keymap?

**Comment by ch11ng** [comment] 2016-08-09 06:00
How do you set the layout and bind the key?

**Comment by spiderbit** [comment] 2016-08-09 19:18
like that:

```
  (push 'menu exwm-input-prefix-keys)
  (define-key xah-fly-key-map (kbd "<menu>") xah-fly-leader-key-map)
```

**Comment by spiderbit** [comment] 2016-08-09 19:50
I tested it on my chromebook, but I cant reproduce the bug, even I share the same emacs config with some host specific settings.

there I use "M-SPC" instead of "menu" for this key-map, there it works. But on that machine on tty I also have dvorak, its a nixos machine.

So my suspicion is that it falls back to systemwide layout? because I cant reproduce it on that machine, I also cant really tell which of the 2 packages introduced the regression.

But still I belive its more likely that exwm caused the bug, because I dont think the changelog in xah-fly-keys is that big for the last few commits I was behind.

**Comment by ch11ng** [comment] 2016-08-10 11:40
You didn't answer how you changed the layout to Dvorak.

I rewrote the key <-> event translation code in ch11ng/xelb@f5216dc13ff44a9f86bdff18272d9b8db1ee7cc5, and that's likely the cause of the problem.

**Comment by spiderbit** [comment] 2016-09-07 15:25
sorry for letting that open so long to answer, I switched my main pc to nixos where I dont hit this bug anymore.

But in Fedora where I had the bug I set it up by xorg config files:

```
        Option "XkbLayout" "us,de,de"
        Option "XkbVariant" "dvorak,nodeadkeys,qwerty"

```

**Comment by ch11ng** [comment] 2016-09-21 10:49
Sorry for the long delay.  I'll try your recipe and see if I can reproduce the bug.

**Comment by ch11ng** [comment] 2016-09-21 13:46
I tried but can't seem to reproduce this issue.  I use the default <kbd>\<f9\></kbd> instead of <kbd>\<menu\></kbd> because I don't have a <kbd>\<menu\></kbd> key.  Can you reproduce this issue with the default <kbd>\<f9\></kbd> key on your Fedora machine? You may also want to check the result of <kbd>C-h k \<menu\> u</kbd>.

**Comment by spiderbit** [comment] 2016-09-21 14:02
I am sorry I had to format that machine cause I did use the whole harddisk for fedora (directly btrfs on /dev/sda) to get my current linux installed, this fedora installation is now only as backup copied to a folder of my fileserver, I dont want to install it here again.

So if you cant reproduce that bug with that information, I think it will be unfixable, as long as I am the only one that run into it, it doesnt really matter that much I guess?

I would have invested it more detailed if I not wanted to switch to another distro anyway.

**Comment by ch11ng** [comment] 2016-09-21 14:21
> So if you cant reproduce that bug with that information, I think it will be unfixable, as long as I am the only one that run into it, it doesnt really matter that much I guess?

>  would have invested it more detailed if I not wanted to switch to another distro anyway.

It fully depends on you.  If this issue doesn't affect you any more and it'll take you a lot of trouble to restore your previous installation, then you'd better close it.  Keyboard issues are usually quite prevalent and can be reproduced in various ways, so it's likely someone else will encounter it.

**Comment by ch11ng** [comment] 2018-10-21 15:14
The relevant features have been reworked.  So I'd assume this issue is fixed and I'm closing it now.  Please  reopen it if the problem is still there.

**Closed by ch11ng** 2018-10-21 15:14 UTC
