### ISSUE TITLE
Screen flickering on Input

### ISSUE THREAD

**Issue by guskovd** [ch11ng/exwm#435] opened 2018-05-24 17:26 UTC
Archlinux
Emacs 25.3.4

After updating to version 25.3.4, exwm began to behave strangely. In firefox (line-mode), when you type text, the screen flickers. In char-mode, everything is fine

**Comment by guskovd** [comment] 2018-05-24 19:52
I understand that this is not related specifically to the new version of emacs.

Rollback to the previous version did not solve the problem. Apparently, I need to roll back some other package. But I do not know what

**Comment by CoderTillDeath** [comment] 2018-05-26 18:38
I have this issue on arch linux as well. The breaking change for me has been updating the X server from version 1.19.6 to 1.20.0, not updating emacs.

**Comment by ch11ng** [comment] 2018-05-27 15:39
I can confirm this.  Many changes have landed in the Xserver 1.20 release.  Still digging through its source.

**Comment by Stebalien** [comment] 2018-06-02 09:11
It looks like windows aren't being properly focused, or something like that...

1. If I run `xdo activate -N Firefox`, it'll correctly activate my firefox window but won't give it keyboard focus.
2. If I then click on the Firefox window, it will gain full focus *and* doesn't flicker on input.
3. This window appears to retain this property. If I switch to a different window and back, I again won't get keyboard focus until I click and again typing doesn't cause any focus flicker (once I click).

**Comment by Stebalien** [comment] 2018-06-02 09:35
So, always using WM_TAKE_FOCUS in `exwm-input--set-focus` appears to fix this. Is the `exwm--hints-input` conditional backwards (and did xorg fix a bug?)?

**Comment by tohojo** [comment] 2018-06-02 15:43
Steven Allen <notifications@github.com> writes:

> So, always using WM_TAKE_FOCUS in `exwm-input--set-focus` appears to
> fix this. Is the `exwm--hints-input` conditional backwards (and did
> xorg fix a bug?)?

This does help the behaviour on Firefox for me as well, but only on the
machine where exwm is working (i.e., no cursor issues). On the other
machine, it makes no difference.

Another weird thing on the broken machine: When I run a terminal (uxrvt
in exwm char mode), I cannot type in it; instead, I get 'buffer is
read-only' errors in the Emacs modeline. However, if I mash a bunch of
keys at once (i.e., if input happens really quickly), *some* of the
characters are passed through to the terminal...

**Comment by tohojo** [comment] 2018-06-02 15:56
Toke Høiland-Jørgensen <toke@toke.dk> writes:

> Steven Allen <notifications@github.com> writes:
>
>> So, always using WM_TAKE_FOCUS in `exwm-input--set-focus` appears to
>> fix this. Is the `exwm--hints-input` conditional backwards (and did
>> xorg fix a bug?)?
>
> This does help the behaviour on Firefox for me as well, but only on the
> machine where exwm is working (i.e., no cursor issues). On the other
> machine, it makes no difference.
>
> Another weird thing on the broken machine: When I run a terminal (uxrvt
> in exwm char mode), I cannot type in it; instead, I get 'buffer is
> read-only' errors in the Emacs modeline. However, if I mash a bunch of
> keys at once (i.e., if input happens really quickly), *some* of the
> characters are passed through to the terminal...

Aha! I did some more investigation, and tracked the weird behaviour to
this line in my .Xmodmap:

`keycode 233 = XF86Forward`

which for the life of me I can't remember why I put there. I have
another one mapping keycode 234 to XF86Back, which does not seem to give
any problems...

Anyway, removing that line causes exwm to work again, and the
WM_TAKE_FOCUS now also improves firefox behaviour in line mode on this
machine :)

**Comment by tohojo** [comment] 2018-06-02 17:06
Toke Høiland-Jørgensen <toke@toke.dk> writes:

> Toke Høiland-Jørgensen <toke@toke.dk> writes:
>
>> Steven Allen <notifications@github.com> writes:
>>
>>> So, always using WM_TAKE_FOCUS in `exwm-input--set-focus` appears to
>>> fix this. Is the `exwm--hints-input` conditional backwards (and did
>>> xorg fix a bug?)?
>>
>> This does help the behaviour on Firefox for me as well, but only on the
>> machine where exwm is working (i.e., no cursor issues). On the other
>> machine, it makes no difference.
>>
>> Another weird thing on the broken machine: When I run a terminal (uxrvt
>> in exwm char mode), I cannot type in it; instead, I get 'buffer is
>> read-only' errors in the Emacs modeline. However, if I mash a bunch of
>> keys at once (i.e., if input happens really quickly), *some* of the
>> characters are passed through to the terminal...
>
> Aha! I did some more investigation, and tracked the weird behaviour to
> this line in my .Xmodmap:
>
> `keycode 233 = XF86Forward`
>
> which for the life of me I can't remember why I put there. I have
> another one mapping keycode 234 to XF86Back, which does not seem to give
> any problems...
>
> Anyway, removing that line causes exwm to work again, and the
> WM_TAKE_FOCUS now also improves firefox behaviour in line mode on this
> machine :)

Another observation: Enabling WM_TAKE_FOCUS breaks pinentry-qt (which
tries to globally grab input, I think).

**Comment by ch11ng** [comment] 2018-06-03 08:38
@Stebalien Thank you for the finding.  I believe according to ICCCM we should not send WM_TAKE_FOCUS but use SetInputFocus directly for the so called 'locally active mode' X windows (I may misunderstand that pedantic spec).  Perhaps some relevant change had been made.

**Comment by ch11ng** [comment] 2018-06-03 12:36
This change was introduced by https://cgit.freedesktop.org/xorg/xserver/commit/?id=c67f2eac56518163981af59f5accb7c79bc00f6a , with which apps would receive extra FocusIn/FocusOut events when keyboard is grabbed.  I can't tell if this change is reasonable, but the problem is:

* EXWM would grab keyboard in line-mode in order to intercept key events.
* X server would send extra events to notify focus change when keyboard is grabbed (they are notifications only; input focus is not changed actually).
* Apps like Firefox would 'do something' when there is an input focus change (even if it's not real).

No idea how to resolve this yet, but it seems little can be done on our side.

**Comment by tohojo** [comment] 2018-06-03 12:58
Chris Feng <notifications@github.com> writes:

> This change was introduced by https://cgit.freedesktop.org/xorg/xserver/commit/?id=c67f2eac56518163981af59f5accb7c79bc00f6a , with which apps would receive extra FocusIn/FocusOut events when keyboard is grabbed.  I can't tell if this change is reasonable, but the problem is:
>
> * EXWM would grab keyboard in line-mode in order to intercept key
> events.

Does this happen on every key press? I'm not too familiar with the X
protocol, but is there no way to avoid grab events except when the mode
changes?

> * X server would send extra events to notify focus change when keyboard is grabbed (they are notifications only; input focus is not changed actually).
> * Apps like Firefox would 'do something' when there is an input focus change (even if it's not real).
>
> No idea how to resolve this yet, but it seems little can be done on
> our side.

Well, if nothing can be done, opening a bug against firefox might be the
way forward; but that seems like it would be a long game of whack-a-mole
with applications that do weird things...

**Comment by ch11ng** [comment] 2018-06-03 16:41
The problem is what we want to 'grab' are key sequences, so theoretically any key may get checked when necessary.  Grabbing dynamically requires constantly issuing grab/ungrab requests, which can result in timing problems.

**Comment by dakra** [comment] 2018-06-03 20:14
> Well, if nothing can be done, opening a bug against firefox might be the way
> forward

Just want to add that it also happens in the pidgin username dropdown.
So in an open pidgin conversation press 'C-m' to start texting a
new buddy, add partial name and try selecting it with up/down (C-n/C-p for me)
that doesn't work anymore.
So it's not only Firefox that's affected.

**Comment by ch11ng** [comment] 2018-06-04 15:55
@Stebalien This sounds tricky but I'll give a try.

**Comment by Stebalien** [comment] 2018-06-04 15:58
You could also try asking the Xorg devs if there is a better solution. However, I'm pretty sure most key-chord hotkey binding programs (e.g., sxhkd) use this "grab the prefix only" method (for performance reasons).

**Comment by ch11ng** [comment] 2018-06-11 16:41
@Stebalien As I tried your suggestion I found it difficult to figure out which keys should be grabbed.  Emacs is quite flexible at processing keys: `extra-keyboard-modifiers`, `keyboard-translate-table`, `input-decode-map`, `local-function-key-map`, `key-translation-map`, `overriding-terminal-local-map` ... all can alter the meaning of keys.  Besides there are other aspects to take into consideration.

In the meantime I've been trying with the XI2 extension to grab and replay keys.  From the source of Xorg server it appears if we grab 'slave devices' those annoying events won't be generated. No much process has been made on this yet but at least XI2 works after some fixes.

**Comment by dakra** [comment] 2018-06-11 19:15
@Stebalien thanks. I just evaled your snippet and can confirm that it also solves the focus problem I had (firefox navbar and pidgin new message contact popup) :+1:

**Comment by tohojo** [comment] 2018-06-11 19:29
Daniel Kraus <notifications@github.com> writes:

> @Stebalien thanks. I just evaled your snippet and can confirm that it
> also solves the focus problem I had (firefox navbar and pidgin new
> message contact popup) :+1:

Yup, seems to work for me as well; thanks! :)

**Comment by ch11ng** [comment] 2018-06-18 16:24
@Stebalien I'm not sure how your snippet works around the problem.  It worth further investigations of course.

Anyway I've given up replaying key events with the core protocol, but I'm surprised to learn XI2 cannot do replay for slave keyboards (it does work for the master).  If someone know how to do that, please tel me.  For now I turn to XTEST and it basically works.  I'm afraid something may be broken with this change so please give as much test as you can.

**Comment by Stebalien** [comment] 2018-06-18 17:24
That change appears to break my electron-based slack. For some reason, exwm doesn't capture *any* events when I first start it. After some messing around, it started capturing events however, when I tried to close slack, I started running into weird focus issues.

**Comment by dakra** [comment] 2018-06-18 20:44
The last xelb and exwm updates break things for me too. Most noticeable is that CapsLock which normally is mapped to Control is really CapsLock but only in X11 buffers.

**Comment by ch11ng** [comment] 2018-07-15 11:18
Considering the regressions introduced in by the last change I've replaced it with @Stebalien's solution.  Sending an extra `WM_TAKE_FOCUS` event doesn't seem to cause any side-effect.  I have to admit it's a good solution for it does solve the problem, though the theory behind it is not clear.

**Comment by medranocalvo** [comment] 2018-10-08 16:32
This seems to be working all right.  @ch11ng, shall we close this ticket?

**Comment by ch11ng** [comment] 2018-10-14 07:56
@medranocalvo I think so.  We ended up with @Stebalien's solution and it works fine.  @Stebalien thanks!

**Closed by ch11ng** 2018-10-14 07:56 UTC
