### ISSUE TITLE
ido-kill-buffer-at-head functionality not working properly

### ISSUE THREAD

**Issue by guskovd** [ch11ng/exwm#147] opened 2016-03-30 14:06 UTC
ido completions must be updated after C-k pressing on exwm buffer

**Comment by ch11ng** [comment] 2016-03-31 11:51
I don't use this feature very often but isn't the `*Ido Completions*` buffer not updated even you press <kbd>C-k</kbd> when visiting a non-EXWM buffer?

**Comment by guskovd** [comment] 2016-03-31 12:24
C-k is working properly on regular emacs buffers

**Comment by ch11ng** [comment] 2016-03-31 13:32
Well, I was confused by several `ido-*` functions.  So the problem is that `exwm-mode` buffers are often not killed directly until the corresponding X windows get destroyed (`exwm-manage--kill-buffer-query-function`).  This makes Ido believe that the buffers can not be killed and the completions won't be updated.  I can't work out a solution though; simply calling `(exit-minibuffer)` seems dirty.  Does anyone have any idea?

**Comment by ch11ng** [comment] 2016-07-30 02:30
It seems we have to exit the minibuffer or we'll get the "selecting deleted buffer" error eventually.  So I pushed a fix (aa7de9dc6f13b0d937fe265b64368b7be6e8798e) without updating ido completions.

**Closed by ch11ng** 2016-07-30 02:30 UTC
