### ISSUE TITLE
EXWM buffers don't capture focus (Buffer becomes read only)  on multi-monitor setup.

### ISSUE THREAD

**Issue by farazshaikh** [ch11ng/exwm#714] opened 2020-02-20 02:20 UTC
Hello Authors, 

Thanks for providing such a useful emacs package. 
A bug has hit my multi-monitor setup after upgrading from 0.21 to 0.23.
Selecting the exwm buffer ACROSS monitors using the mouse click is not restoring window-focus on the selected buffer (thus keyboard-capture).

I have zeroed down the errant behavior to the following changes.

commit c5794765362460b5c18fdedb3f77617fb34ee804
Date:   Sun Jul 28 00:00:00 2019 +0000
    Fix `after-focus-change-function' not working
    
    * exwm-workspace.el (exwm-workspace--original-handle-focus-in)
    (exwm-workspace--original-handle-focus-out): Store the original
    `handle-focus-{in,out}'.
    (exwm-workspace-switch): Now that `handle-focus-{in,out}' has been
    updated to call other stuffs like `after-focus-change-function', we
    can no longer run `focus-{in,out}-hook' only.

Steps To Reproduce. 
1. 2 monitors (exwm-randr) laptop and desktop monitor.
2. On each monitor, open a Terminal and firefox window side by side. 
```
    Desktop 1 [Workspace1]
    [                 ][               ]
    |  Terminal       || Browser       |
    [                 ][               ]
 


   Laptop   [Workspace2]
    [                 ][               ]
    |  Terminal       || Browser       |
    [                 ][               ]
```

3. Moving from one workspace across to the other , using the mouse to click inside the exwm buffer.
4. The exwm buffer selected using the mouse click doesn't capture focus unless its MODE LINE is clicked anywhere. 

Workaround. 
Once you switch from one workspace to other and use the mode-line to capture focus, everything in that workspace continues to work until you switch to the other workspace.

**Comment by ch11ng** [comment] 2020-03-01 14:01
I tried EXWM 0.23 and couldn't seem to reproduce this issue.  Do you have anything special setup relating to input focus? Perhaps you want to try the latest code from source.  There are some fixes since the 0.23 release.

**Comment by farazshaikh** [comment] 2020-03-11 21:15
I narrowed down the interaction to exwm and centaur-tabs package. 

Repro should be:
start emacs 
load exwm
load centaur tabs
start chrome
google-chrome buffer goes read-only.


The bug rendered my setup pretty unusable as I had to mouse-click the modeline to do any window-change interactions.

I have disabled centaur tabs as I didn't find myself using the tabs functionality much. 
Please free close the bug/investigate the interaction further.

**Comment by ch11ng** [comment] 2020-03-15 06:36
Tried your latest recipe and failed to reproduce it again.  Perhaps you customized centaur-tabs in some way?

**Comment by simmihugs** [comment] 2020-05-14 19:28
Firefox does go read-only for me - not always but most of the times when switch away to another workspace and switch back to the workspace where the firefox instance lives.

When I execute `M-x RET XX` where `XX` are some random keys I can most of the times regain the focus on firefox (that's not a fix but it might help someone who knows `exwm` to diagnose whats going on + it is a good enough _solution_ for me to try out `exwm`)

same happens sometimes for other applications - but it is less frequent 

I use emacs 26.3 on Linux (my own config) and I use the [default example](https://github.com/ch11ng/exwm/wiki/Configuration-Example) of the `exwm` setup from the `exwm` wiki minus ido (I'm pretty much a newbie with emacs)

**Comment by ch11ng** [comment] 2020-05-16 06:27
@simmihugs It might not be relevant but are you able to reproduce this bug with c7c42582b7342f20c22b8a040eab72d3ce9f37b5?

**Comment by simmihugs** [comment] 2020-05-16 15:10
hi @ch11ng thanks for your quick response

I just tried this and it solves the problem - I edited the file `exwm-workspace.el` accordingly to  [https://github.com/ch11ng/exwm/commit/c7c42582b7342f20c22b8a040eab72d3ce9f37b5](c7c4258). Removed the byte-complied version and run `byte-compile-file` on the `*.el` file

when I move from a Workspace where Firefox is running to any other workspace and back -> Firefox is in focus yeah

But I now discovered another problem, when I have a Workspace with Firefox fullscreen and I split the Screen to have two buffers `C-x 3` and launch eshell on the right side `C-x C-o` `M-x RET eshell` and switch focus to it and switch back to Firefox with `C-x C-o` -> The buffer is read-only yet again

Moving to another workspace and back fixes this again -> Firefox in focus

I have to add - it seams this is an issue I only having with firefox
other apps like nautilus or other apps seam to work
As I use firefox mostly in fullscreen it's usable

I think this is not related to this issue then?

**Comment by ch11ng** [comment] 2020-05-17 08:54
@simmihugs 

> [...] when I have a Workspace with Firefox fullscreen and I split the Screen to have two buffers `C-x 3` [...]

How is it possible to do the split with an X window in fullscreen mode? Did you mean Firefox was the only X window on that workspace? If so, please prepare debug logs according to https://github.com/ch11ng/exwm/wiki#how-to-report-a-bug so we can see where goes wrong.

**Comment by simmihugs** [comment] 2020-05-17 13:51
Firefox was the only x window on a workspace. Then all the things I described above ... however I just read your mail, tried to recreated this behaviour and now it works for some reason - firefox and other buffers on the same workspace let me switch via `C-x o` ...

As weird it is, I'm happy it works now ... I guess

Anyway thank you @ch11ng 

In case I encounter this problem again I will use the link you posted above to report a bug

**Comment by medranocalvo** [comment] 2020-05-20 14:36
I'm closing this now, please reopen if you encounter it again.

**Closed by medranocalvo** 2020-05-20 14:36 UTC
