### ISSUE TITLE
Global key bindings not working in char-mode

### ISSUE THREAD

**Issue by Inops** [ch11ng/exwm#208] opened 2016-10-26 15:12 UTC
Just trying out exwm. I'm running the current git version, but I tried it with the 0.11 release and have the same problem. (exwm-config-default)'s `s-r`, `s-&` and `s-w` bindings work as expected in line-mode, but don't seem to be received in char-mode. I have to use the mouse to exit char-mode. My exwm config is the one in the user guide.:

```
(add-to-list 'load-path "~/exwm/")
(require 'exwm)
(require 'exwm-config)
(exwm-config-default)
```

and I've had the problem just init'ing with this, and not the rest of my emacs init file.

**Comment by ch11ng** [comment] 2016-10-31 14:40
Sorry for the delay.  I'll check this in a few days.

**Comment by ch11ng** [comment] 2016-11-02 13:44
Could you provide more details? I don't think I can reproduce it.  You may try to invoke `exwm-input-set-key` after EXWM is started and see if it works.

**Comment by wsgac** [comment] 2016-11-03 09:34
I have a question which might not be unrelated. I've defined a function for cycling through several keyboard layouts in X. When run directly in Elisp or in a normal Emacs buffer in EXWM it works as expected. Now in my EXWM config function I added the following expression:
`(exwm-input-set-key (kbd "s-SPC") #'toggle-keyboard-layout)`
This binding also works fine in normal text buffers, but not in X applications, e.g. Chrome. I've tried both char-mode and line-mode and it seems the <kbd>Super</kbd> key in this binding is somehow ignored, while the <kbd>Space</kbd> is passed to the X program. I've also tried a different binding, not using the <kbd>Super</kbd> key (<kbd>M-g M-l</kbd>), but to no avail. Any thoughts on how I could make this work?

**Comment by ch11ng** [comment] 2016-11-03 14:04
@wsgac,

According to your report, it seems it doesn't matter which command is bound (if `toggle-keyboard-layout` does not change the mapping of modifier keys).  You may try to bind another command and see if the problem persists.

Perhaps the modifier keys are not correctly recognized.  Please check the values of `xcb:keysyms:super-mask` and `xcb:keysyms:meta-mask` and see if they are zero.  OTOH <kbd>control</kbd> keys are fixed so they should work if it is the problem.

**Comment by wsgac** [comment] 2016-11-03 14:14
I tried to bind another command and the problem persists. I've also looked at the variables `xcb:keysyms:super-mask` and `xcb:keysyms:meta-mask`. They had the values 64 and 8 respectively. I tried setting them to 0 but then they got reset to their original values after first use.

**Comment by ch11ng** [comment] 2016-11-05 15:46
To be clear the variables should not be zero.  64 (MOD4) and 8 (MOD1) seem correct.  Could you provide the output of `xmodmap` so that we can make further check?

Also, do you change modifier keys in `toggle-keyboard-layout`? And could you try keys with only <kbd>control</kbd> modifier?

**Comment by ch11ng** [comment] 2016-11-05 15:50
To be clear the variables should not be zero.  64 (MOD4) and 8 (MOD1) seem correct.  Could you provide the output of `xmodmap` so that we can make further check?

Also, do you change modifier keys in `toggle-keyboard-layout`? And could you try keys with only <kbd>control</kbd> modifier?

**Comment by sakshamsharma** [comment] 2016-12-09 08:24
I've noticed that this issue is partially reproducible. This may help:
Not all global bindings work in char-mode. Some do. The ones which do not work are the ones which are captured by the application. For instance, here are some bindings which do not work: `M-3`, `M-4` when you are using google-chrome. These bindings switch to tab 3 or 4 on Chrome. I bind them to volume change, but it doesn't work. This works normally for other window managers. But my media key bindings work fine enough.
What is needed is a way to specify some bindings which are bound globally overriding all other bindings. The current binding system `exwm-input-set-key` seems to only bind as long as the application does not capture it.

**Comment by ch11ng** [comment] 2016-12-11 12:50
@sakshamsharma This should not happen usually as I've just verified.  I don't think Chrome grabs these keys.  You can use `xev` to check the X events (<kbd>M-1</kbd> for example):

```
KeyPress event, serial 34, synthetic NO, window 0x1e00001,
    root 0xb2, subw 0x1e00002, time 10536306, (35,36), root:(744,363),
    state 0x8, keycode 10 (keysym 0x31, 1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XmbLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False
```

As is shown the keycode is `10` and state is `0x8` so the keysym is `49` (`0x31`):
```
(xcb:keysyms:keycode->keysym exwm--connection 10 #x08)
  => (49 . 1)
```

It follows the key event is `?\M-1` (`134217777`)
```
(xcb:keysyms:keysym->event exwm--connection 49 #x08)
  => 134217777
```

Can you get the same results? How about without numerical keys?

**Comment by sakshamsharma** [comment] 2016-12-11 13:27
This is interesting. `M-3, M-4` seem to be working in both char and line mode as expected, today. I suppose restarting emacs fixed this for me. There was another issue of my manually added prefixes not working. Even that seems fixed today.

**Comment by Sbozzolo** [comment] 2017-01-08 20:16
Same here! I cannot get Chrome to not grab <kbd>F12</kbd> (bounded to `org-capture`), instead it opens the developer tools, nor <kbd>ALT</kbd> + <kbd>TAB</kbd>, which I bounded to ` iflipb-next-buffer`. Conversely, binding those commands to `C-c <f12>` works as expected.  Running `xev` in a `term` buffer on <kdb>F12</kbd> gives this result (I think):

```
KeyPress event, serial 31, synthetic NO, window 0x1800001,
    root 0xd9, subw 0x0, time 732929, (411,412), root:(1211,412),
    state 0x0, keycode 96 (keysym 0xffc9, F12), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Evaluating
```
(xcb:keysyms:keycode->keysym exwm--connection 96 #x0)
```
Gives `(65481 . 141)`. And 
```
(xcb:keysyms:keysym->event exwm--connection 65481 #x00)
```
Gives `f12`, which I suppose is right. Nevertheless in chromium those keys don't work as I want in line
nor char mode.

**Comment by ch11ng** [comment] 2017-01-10 14:36
@Sbozzolo I tried both keys and they were working as expected.  Please check if they appear in `exwm-input--global-keys` and `exwm-input--global-prefix-keys`.

As for <kbd>alt-tab</kbd>, it matters which form is used: In Emacs it's usually referred to as <kbd>C-M-i</kbd> (note <kbd>C-i</kbd> is <kbd>tab</kbd>) so it's an integer (134217737).  Whereas it can also be represented by <kbd>M-tab</kbd> (which is a symbol `'M-tab`).  Only the latter form can be recognized by EXWM for now.

**Comment by Sbozzolo** [comment] 2017-01-10 17:17
I don't know what I've done but now they both works in chromium.

**Comment by ch11ng** [comment] 2018-10-21 15:08
This feature has been reworked since this issue was reported.  I'd assume the problem is resolved and I'm closing this issue now.  Please reopen it if the problem is still there.

**Closed by ch11ng** 2018-10-21 15:08 UTC
