### ISSUE TITLE
EXWM assumes QWERTY in X11 buffers

### ISSUE THREAD

**Issue by yegortimoshenko** [ch11ng/exwm#293] opened 2017-08-13 12:39 UTC
To reproduce, set [`xkbVariant`](https://www.x.org/archive/X11R7.5/doc/input/XKB-Config.html) to `"colemak"`, open any X11 application (say, Chromium) and try closing the buffer using C-c C-k. Only in X11 buffers, instead of using Colemak layout, it will for some reason I don't really understand use QWERTY layout, which means C-c C-k will be  registered as C-c C-n.

In non-X11 buffers C-c C-k works as expected, using the layout I've specified in `xkbVariant` option.

**Comment by ch11ng** [comment] 2017-08-20 16:41
How did you set up the layout and the <kbd>C-c C-k</kbd> key? I tried `setxkbmap -v us -variant colemak` and <kbd>C-x C-k</kbd> and things seemed working.

**Comment by Gamayun** [comment] 2017-09-26 18:28
I seem to have the same issue. Only seems to affect the EXWM prefix keys and simulation keys though, not the keys that are passed to the application itself. `setxkbmap -layout gb -variant dvorak` in my case doesn't make a difference. I've had it working normally with same layout in GuixSD previously; not working in Ubuntu 16.04.

**Comment by technomancy** [comment] 2017-10-07 00:30
It works fine for me in Dvorak, but like @Gamayun I set my layout before Emacs loads.

**Comment by ch11ng** [comment] 2017-10-08 15:17
That's strange.  XELB registers the XKB `MapNotify` event by default.  Which version of Xorg do you use?

PS.  I usually remap keys with hwdb so the experiences are consistent under console and X11.  And it's less error-prone.

**Comment by ch11ng** [comment] 2017-11-26 08:16
`setxkbmap` makes an `XkbGetKeyboardByName` request to modify keyboard mapping, and XELB will receive an `XkbNewKeyboardNotify` event as a result.  Currently XELB handles this event differently than Xlib that it only selectively updates the local cache while Xlib simply invalidate all.  This may be the cause of the issue.  As I have never reproduced the bug, could someone try (some of) the following forms and see if they can resolve the problem?

```elisp
(xcb:keysyms:-update-keytypes exwm--connection xcb:keysyms:-device)

(xcb:keysyms:-update-keycodes exwm--connection xcb:keysyms:-device)

(xcb:keysyms:-update-modkeys exwm--connection xcb:keysyms:-device)
```

If not, please report the version of `setxkbmap` and X server with `setxkbmap -version` and `Xorg -version`.

**Comment by ransomts** [comment] 2018-01-13 19:09
Running `(xcb:keysyms:-update-keycodes exwm--connection xcb:keysyms:-device)` was enough to get it right on my system. Thanks!

**Comment by ch11ng** [comment] 2018-01-14 16:07
@ransomts That form is not intended to be run by the user manually; it should be triggered by some events.  Unfortunately I've not found the exact cause of this.  I'd be nice if someone could provide a reliable way to reproduce this bug.

**Comment by Follpvosten** [comment] 2018-03-25 16:41
I am also having this bug; with a qwertz layout (keymap `de`, set via Xorg config files), i have to use C-z to paste in EXWM buffers (and also s-z to start applications, as i set it to s-y). It wouldn't be an issue if that was the case in every buffer, but since it's only X window buffers, it's certainly annoying. (I also can't run the commands to fix it, it's telling me "Wrong type argument: number-or-marker-p, xcb:keysyms:-device", am i missing something?)
This is on a FreeBSD 11.1 machine with Xorg version 1.18.4 (quarterly branch of packages)

**Comment by ch11ng** [comment] 2018-04-01 15:50
This should be fixed with ch11ng/xelb@eda5f25b14959592cb4c75ea52fe7526fe13d91f .

**Comment by ch11ng** [comment] 2018-10-21 14:48
Similar issues have been reported and fixed later.  So I'm assuming this one got fixed too.  I'm closing this issue now.  Please reopen it if the problem is still there.

**Closed by ch11ng** 2018-10-21 14:48 UTC

**Comment by codemac** [comment] 2019-03-20 23:39
I have this problem when udev events are used to trigger a keyboard remapping - exwm-restart solved the keyboard problem.

I have a laptop keyboard in dvorak, and a desktop keyboard in US (that is remapped in hardware all over the place). The desktop keyboard is hot plugged repeatedly throughout the day.  

I am currently using exwm-0.22.1 and xelb-0.17.

**Comment by codemac** [comment] 2019-03-21 17:26
```
exwm-input--on-PropertyNotify:	
exwm-input--on-KeyPress:	major-mode=exwm-mode buffer=Google-chrome
exwm-input--on-KeyPress-line-mode:	(121 . 3)
exwm-input--mimic-read-event:	
exwm-input--cache-event:	25
exwm-input--on-KeyPress:	major-mode=exwm-mode buffer=Google-chrome
exwm-input--on-KeyPress-line-mode:	(65507 . 0)
exwm--on-PropertyNotify:	atom=_NET_WM_USER_TIME(361)
exwm-input--on-PropertyNotify:	
exwm-input--on-KeyPress:	major-mode=exwm-mode buffer=Google-chrome
exwm-input--on-KeyPress-line-mode:	(116 . 3)
exwm-input--mimic-read-event:	
exwm-input--cache-event:	24
```

Here we see the laptop & the attached USB keyboard's KeyPress-line-mode saying different things:

- `(116 . 3)` for the laptop's keyboard
- `(121 . 3)` for the USB

I can see the grab-keyboard notifications, but I don't see where it refreshes the keyboards. exwm-restarte fixes the issue.

**Comment by codemac** [comment] 2019-03-21 20:17
Oh: after exwm-restart, the usb keyboard is sending 116 instead of 121.

**Comment by ch11ng** [comment] 2019-03-24 11:33
@codemac Does the result of `(xcb:-get-extra-plist exwm--connection 'keysyms 'device-id)` change when you switch between keyboards?  And what's result of the following sexp?

```elisp
(cl-loop for i in (plist-get (slot-value exwm--connection 'extra-plist) 'keysyms) by #'cddr collect i)
```

**Comment by codemac** [comment] 2019-03-25 20:02
Looks like I get the same result in both ways.

```
** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (xcb:-get-extra-plist exwm--connection 'keysyms 'device-id)
3 (#o3, #x3, ?\C-c)
ELISP> (cl-loop for i in (plist-get (slot-value exwm--connection 'extra-plist) 'keysyms) by #'cddr collect i)
(opcode callback 3 device-id)
```
I plug in to dock
```
ELISP>  (xcb:-get-extra-plist exwm--connection 'keysyms 'device-id)
3 (#o3, #x3, ?\C-c)
ELISP> (cl-loop for i in (plist-get (slot-value exwm--connection 'extra-plist) 'keysyms) by #'cddr collect i)
(opcode callback 3 device-id)

ELISP> 
```

Then I do exwm-restart:

```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP>  (xcb:-get-extra-plist exwm--connection 'keysyms 'device-id)
3 (#o3, #x3, ?\C-c)
ELISP> (cl-loop for i in (plist-get (slot-value exwm--connection 'extra-plist) 'keysyms) by #'cddr collect i)
(opcode callback 3 device-id)

ELISP> 
```

So it doesn't look like these are changing.

**Comment by codemac** [comment] 2019-03-25 21:20
Also, xinput list shows that device id=3 is the main Virtual keyboard device:

```
; xinput list | grep 'id=3'
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
```

**Comment by ch11ng** [comment] 2019-03-31 13:19
So XELB only recognized one keyboard.

What's the full output of `xinput`? If your keyboards are slave devices to the 'Virtual core keyboard', perhaps we can not distinguish between different keyboards and can not tell when you switch to another keyboard without the XI2 protocol (I have no enough understanding of the XI2 protocol right now so this statement might not be true).

I also noticed some guides indicting `setxkbmap` is required to setup different keymaps on multiple keyboards.  Could you tell us something more about your settings? I personally have no such experience and can't really tell what's the correctly way to do that.

**Comment by divansantana** [comment] 2022-12-24 15:00
I still have this issue with xelb 0.18 and exwm 0.27.

In X11 buffers line mode or char mode, exwm prefix keys are still mapped to qwerty and not dvorak.

I am on openbsd and my dvorak map is set it /etc/kbdtype which is before X & emacs starts.

Adding `setxkbmap -layout us -variant dvorak` to my `.xsession` file before my xmodmap and xcape command, resolves the issue for me.
