### ISSUE TITLE
exwm-input-set-key fails when key is not ASCII

### ISSUE THREAD

**Issue by Sbozzolo** [ch11ng/exwm#746] opened 2020-05-07 06:21 UTC
Steps to reproduce (EXWM v 0.23, XELB v 0.18):
- `M-x exwm-input-set-key`
- Insert μ
- Bind to any command

The operation will fail with the following backtrace:
```
  backtrace()
  #f(compiled-function (&rest _) #<bytecode 0x158b99f65559>)(error (wrong-type-argument number-or-marker-p nil))
  #f(compiled-function (obj keysym) "Convert keysym to (the first matching) keycode.\n\nReturn 0 if conversion fails." #<bytecode 0x158b9a085985>)(#<xcb:connection xcb:connection-158b9a30c148> nil)
  apply(#f(compiled-function (obj keysym) "Convert keysym to (the first matching) keycode.\n\nReturn 0 if conversion fails." #<bytecode 0x158b9a085985>) #<xcb:connection xcb:connection-158b9a30c148> nil)
  xcb:keysyms:keysym->keycode(#<xcb:connection xcb:connection-158b9a30c148> nil)
  exwm-input--grab-global-prefix-keys(4194305 8388609 8388939 8388967 10485761 10485782 10485762 10485783 10485781)
  apply(exwm-input--grab-global-prefix-keys (4194305 8388609 8388939 8388967 10485761 10485782 10485762 10485783 10485781))
  exwm-input--update-global-prefix-keys()
  exwm-input--on-keysyms-update()
  #f(compiled-function (obj data) "Handle 'MapNotify' event." #<bytecode 0x158b9a0856d1>)(#<xcb:connection xcb:connection-158b9a30c148> [85 1 253 9 18 254 51 0 3 0 18 0 8 255 0 0 66 1 66 1 0 0 0 0 0 0 0 0 0 0 0 0])
  apply(#f(compiled-function (obj data) "Handle 'MapNotify' event." #<bytecode 0x158b9a0856d1>) #<xcb:connection xcb:connection-158b9a30c148> [85 1 253 9 18 254 51 0 3 0 18 0 8 255 0 0 66 1 66 1 0 0 0 0 0 0 0 0 0 0 0 0])
  xcb:keysyms:-on-MapNotify(#<xcb:connection xcb:connection-158b9a30c148> [85 1 253 9 18 254 51 0 3 0 18 0 8 255 0 0 66 1 66 1 0 0 0 0 0 0 0 0 0 0 0 0])
  #f(compiled-function (data _) #<bytecode 0x158b9931e8bd>)([85 1 253 9 18 254 51 0 3 0 18 0 8 255 0 0 66 1 66 1 0 0 0 0 0 0 0 0 0 0 0 0] nil)
  #f(compiled-function (conn) "Process cached events." #<bytecode 0x158b99f6558d>)(#<xcb:connection xcb:connection-158b9a30c148>)
  apply(#f(compiled-function (conn) "Process cached events." #<bytecode 0x158b99f6558d>) #<xcb:connection xcb:connection-158b9a30c148> nil)
  xcb:-process-events(#<xcb:connection xcb:connection-158b9a30c148>)
  xcb:-connection-filter(#<process XELB> "U\1\375\11\22\3763\0\3\0\22\0\10\377\0\0B\1B\1\0\0\0\0\0\0\0\0\0\0\0\0\"\0\375\11\1B\1\0\0\0\0\0\0\0\0\0\0\0...")
```
I noticed that if I manually call `(exwm-input--update-global-prefix-keys)`, then the second time it works.

**Comment by ch11ng** [comment] 2020-05-10 13:20
I managed to map <kbd>f9</kbd> to <kbd>µ</kbd> by setting xmodmap with `keycode 75 = mu mu mu mu`.  But yours have an integer value of 956 while with mine it's 181.  It turns out yours are in Unicode and I have no idea how to input it without any input method.  Anyway, once get it done you can perform verification with something like:

```elisp
(xcb:keysyms:event->keysym exwm--connection ?µ)
   => (181 . 0)
```

Make sure the output is not `nil`.

**Comment by Sbozzolo** [comment] 2020-05-10 16:50
I use xmodmap as well:
```
remove Lock = Caps_Lock
keycode 66 = mu
```

**Comment by ch11ng** [comment] 2020-05-16 06:06
That should be fine then (maybe you copied the character from somewhere else).

You have other special characters like ŋ and ŧ used in global keys.  Are they defined on your keyboard?

**Comment by Sbozzolo** [comment] 2020-05-16 23:09
I am using a standard US keyboard. It is possible that I copied the backtrace in a dirty environment. 

The following should be from a clean env:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  #f(compiled-function (obj keysym) "Convert keysym to (the first matching) keycode.\n\nReturn 0 if conversion fails." #<bytecode 0x1577aeb290c5>)(#<xcb:connection xcb:connection-1577aeb15708> nil)
  apply(#f(compiled-function (obj keysym) "Convert keysym to (the first matching) keycode.\n\nReturn 0 if conversion fails." #<bytecode 0x1577aeb290c5>) #<xcb:connection xcb:connection-1577aeb15708> nil)
  xcb:keysyms:keysym->keycode(#<xcb:connection xcb:connection-1577aeb15708> nil)
  exwm-input--grab-global-prefix-keys(6291480 6291479 6291478 4194305 4194635 6291457 6291477 6291458 4195674 6291481)
  apply(exwm-input--grab-global-prefix-keys (6291480 6291479 6291478 4194305 4194635 6291457 6291477 6291458 4195674 6291481))
  exwm-input--update-global-prefix-keys()
  exwm-input-set-key([8711] switch-to-buffer)
  funcall-interactively(exwm-input-set-key [8711] switch-to-buffer)
  call-interactively(exwm-input-set-key record nil)
  command-execute(exwm-input-set-key record)
  execute-extended-command(nil "exwm-input-set-key" "exwm-input-set-k")
  funcall-interactively(execute-extended-command nil "exwm-input-set-key" "exwm-input-set-k")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

What I did was: bind Caps Lock to ∇ with
```
remove Lock = Caps_Lock
keycode 66 = nabla
```
Start a new instance of EXWM starting from a new TTY with:
```
exec dbus-launch emacs -Q -L /home/sbozzolo/.normal.d/elpa/exwm-0.23/ -L /home/sbozzolo/.normal.d/elpa/xelb-0.18/ \
     --eval "(setq debug-on-error t)" \
     --eval "(setq debug-all-forms t)" \
     --eval "(require 'exwm)" \
     --eval "(require 'exwm-config)" \
     --eval "(exwm-config-default)" \
     --eval "(exwm-init)";
```
Then, 
- `M-x exwm-input-set-key`
- Caps Lock (that is now nabla)
- `switch-to-buffer`.

**Comment by ch11ng** [comment] 2020-05-17 08:59
It seems at least ŋ is still there:

>   exwm-input--grab-global-prefix-keys(6291480 6291479 6291478 4194305 4194635 6291457 6291477 6291458 4195674 6291481)

```elisp
(key-description [4194635])
   => "A-ŋ"
```

It must have been defined somewhere.  There are even some characters won't render on my system.  Is your installation using UTF-8?

**Comment by Sbozzolo** [comment] 2020-05-18 14:55
I am using Emacs 27.0.90 on Gentoo. These are the USE flags:
```
USE="X acl alsa cairo dbus dynamic-loading gconf gfile gif gmp gsettings gtk gzip-el harfbuzz imagemagick inotify jpeg json libxml2 png sound source ssl svg systemd threads tiff xft xpm zlib -Xaw3d (-aqua) -athena -games -gpm -gtk2 -kerberos -lcms -livecd -m17n-lib -mailutils -motif (-selinux) -toolkit-scroll-bars -wide-int -xwidgets"
```
Then I have system configuration features:
```
XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
```
I don't know where to look more specifically.

**Comment by ch11ng** [comment] 2020-05-24 08:57
Does `(key-description [4194635])` produces the same result on your system? If so, what's the value of `exwm-input-global-keys` and are there any configurations using `exwm-input-set-key`?

**Comment by Sbozzolo** [comment] 2020-06-13 15:19
Yes, `(key-description [4194635])` has the same value. 

I updated EXWM to the 0.24, and now I cannot reproduce with the steps in the first post. So, maybe the problem is already fixed.

**Comment by ch11ng** [comment] 2020-06-14 09:55
Now that the problem is reported fixed I'm closing this issue now.

**Closed by ch11ng** 2020-06-14 09:55 UTC
