### ISSUE TITLE
Changing theme takes too long

### ISSUE THREAD

**Issue by CestDiego** [ch11ng/exwm#84] opened 2015-10-15 16:43 UTC
I have been experiencing this since day one but I always thought it was an Spacemacs issue, but after using an ubuntu machine with my same configuration I think it is EXWM the one it's doing something to the loading time for changing themes.

**Comment by ch11ng** [comment] 2015-10-16 04:56
I don't quite get it.  How do you change the theme?  With `load-theme`?  Have you tried to put it at the beginning of `.emacs`?

**Comment by CestDiego** [comment] 2015-10-16 08:01
No. Evaluate loads theme from within emacs with another theme.

**Comment by ch11ng** [comment] 2015-10-16 10:33
This seems to be caused by the extra frames (workspaces) created by EXWM. Can you confirm it?

**Comment by CestDiego** [comment] 2015-10-16 15:04
How could I? ehmmm shall I like just use one workspace?

**Comment by CestDiego** [comment] 2015-10-16 15:06
@ch11ng I just tried using only one workspace, indeed it's that what is causing the delay, I was using 10 workspaces. How can this be solved? D: is this an emacs issue more than EXWM?

**Comment by ch11ng** [comment] 2015-10-17 02:41
I don't quite understand the mechanism of changing color theme in Emacs, but it seems `load-theme` will eventually call `custom-theme-recalc-face` which loops over `(frame-list)`. So this issue seems inevitable.

**Comment by CestDiego** [comment] 2015-10-17 19:02
I guess using EXWM with only one frame and some kind of perspectives then would be a more fitting solution for work spaces for me.

**Comment by ch11ng** [comment] 2015-10-18 01:03
I'm just curious how often you change the color theme.  I think one usually select a color theme an stick to it for months or even years.  Besides, loading the color theme should probably always be done at startup since changing the color theme at runtime may cause some side effects.

Now that this issue is not related to EXWM, I'm closing it.

**Closed by ch11ng** 2015-10-18 01:03 UTC

**Comment by CestDiego** [comment] 2015-10-18 01:06
It's also very slow when opening Magit Status...I now reverted to having only one workspace and magit status loads very quickly.

**Comment by ch11ng** [comment] 2015-10-18 01:09
Perhaps hiding unused workspaces would help, but I'm not sure.

**Comment by CestDiego** [comment] 2015-10-18 01:28
can you replicate the magit status delay though?

**Comment by ch11ng** [comment] 2015-10-18 01:52
No, at least unnoticeable with even 10 workspaces.
